//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEWAXP.Foundation.CustomDB.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EmiratiEventRegistration> EmiratiEventRegistrations { get; set; }
        public virtual DbSet<EventRegistration> EventRegistrations { get; set; }
        public virtual DbSet<PODEventCode> PODEventCodes { get; set; }
        public virtual DbSet<PODEventRegistration> PODEventRegistrations { get; set; }
        public virtual DbSet<raffel> raffels { get; set; }
        public virtual DbSet<WebsiteSearchFeedback> WebsiteSearchFeedbacks { get; set; }
    
        public virtual int PROC_StoreSitemapData(string dumpData)
        {
            var dumpDataParameter = dumpData != null ?
                new ObjectParameter("DumpData", dumpData) :
                new ObjectParameter("DumpData", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_StoreSitemapData", dumpDataParameter);
        }
    
        public virtual int sp_checkraffel(string email, string mobile, ObjectParameter status)
        {
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var mobileParameter = mobile != null ?
                new ObjectParameter("mobile", mobile) :
                new ObjectParameter("mobile", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_checkraffel", emailParameter, mobileParameter, status);
        }
    
        public virtual ObjectResult<SP_EmirateCheckOfflineAllow_Result> SP_EmirateCheckOfflineAllow(Nullable<int> maxofflinecount)
        {
            var maxofflinecountParameter = maxofflinecount.HasValue ?
                new ObjectParameter("maxofflinecount", maxofflinecount) :
                new ObjectParameter("maxofflinecount", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_EmirateCheckOfflineAllow_Result>("SP_EmirateCheckOfflineAllow", maxofflinecountParameter);
        }
    
        public virtual ObjectResult<SP_EmirateEventRegistration_Result> SP_EmirateEventRegistration(Nullable<int> maxofflinecount, string name, string emailid, string designation, string howtoattend, string prno, Nullable<bool> tc, Nullable<bool> hasvaccine, Nullable<bool> hasrtpcr, byte[] vaccinefile, string vaccinefilename)
        {
            var maxofflinecountParameter = maxofflinecount.HasValue ?
                new ObjectParameter("maxofflinecount", maxofflinecount) :
                new ObjectParameter("maxofflinecount", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var emailidParameter = emailid != null ?
                new ObjectParameter("emailid", emailid) :
                new ObjectParameter("emailid", typeof(string));
    
            var designationParameter = designation != null ?
                new ObjectParameter("designation", designation) :
                new ObjectParameter("designation", typeof(string));
    
            var howtoattendParameter = howtoattend != null ?
                new ObjectParameter("howtoattend", howtoattend) :
                new ObjectParameter("howtoattend", typeof(string));
    
            var prnoParameter = prno != null ?
                new ObjectParameter("prno", prno) :
                new ObjectParameter("prno", typeof(string));
    
            var tcParameter = tc.HasValue ?
                new ObjectParameter("tc", tc) :
                new ObjectParameter("tc", typeof(bool));
    
            var hasvaccineParameter = hasvaccine.HasValue ?
                new ObjectParameter("hasvaccine", hasvaccine) :
                new ObjectParameter("hasvaccine", typeof(bool));
    
            var hasrtpcrParameter = hasrtpcr.HasValue ?
                new ObjectParameter("hasrtpcr", hasrtpcr) :
                new ObjectParameter("hasrtpcr", typeof(bool));
    
            var vaccinefileParameter = vaccinefile != null ?
                new ObjectParameter("vaccinefile", vaccinefile) :
                new ObjectParameter("vaccinefile", typeof(byte[]));
    
            var vaccinefilenameParameter = vaccinefilename != null ?
                new ObjectParameter("vaccinefilename", vaccinefilename) :
                new ObjectParameter("vaccinefilename", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_EmirateEventRegistration_Result>("SP_EmirateEventRegistration", maxofflinecountParameter, nameParameter, emailidParameter, designationParameter, howtoattendParameter, prnoParameter, tcParameter, hasvaccineParameter, hasrtpcrParameter, vaccinefileParameter, vaccinefilenameParameter);
        }
    
        public virtual ObjectResult<SP_EventRegistration_Result> SP_EventRegistration(string fullName, string companyName, string country, string designation, string mobile, string email, string eventCode, string sessionName, string institution, string linkUrl)
        {
            var fullNameParameter = fullName != null ?
                new ObjectParameter("FullName", fullName) :
                new ObjectParameter("FullName", typeof(string));
    
            var companyNameParameter = companyName != null ?
                new ObjectParameter("CompanyName", companyName) :
                new ObjectParameter("CompanyName", typeof(string));
    
            var countryParameter = country != null ?
                new ObjectParameter("Country", country) :
                new ObjectParameter("Country", typeof(string));
    
            var designationParameter = designation != null ?
                new ObjectParameter("Designation", designation) :
                new ObjectParameter("Designation", typeof(string));
    
            var mobileParameter = mobile != null ?
                new ObjectParameter("Mobile", mobile) :
                new ObjectParameter("Mobile", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var eventCodeParameter = eventCode != null ?
                new ObjectParameter("EventCode", eventCode) :
                new ObjectParameter("EventCode", typeof(string));
    
            var sessionNameParameter = sessionName != null ?
                new ObjectParameter("SessionName", sessionName) :
                new ObjectParameter("SessionName", typeof(string));
    
            var institutionParameter = institution != null ?
                new ObjectParameter("Institution", institution) :
                new ObjectParameter("Institution", typeof(string));
    
            var linkUrlParameter = linkUrl != null ?
                new ObjectParameter("LinkUrl", linkUrl) :
                new ObjectParameter("LinkUrl", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_EventRegistration_Result>("SP_EventRegistration", fullNameParameter, companyNameParameter, countryParameter, designationParameter, mobileParameter, emailParameter, eventCodeParameter, sessionNameParameter, institutionParameter, linkUrlParameter);
        }
    
        public virtual int sp_insert_raffel(string name, string email, string mobile)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var mobileParameter = mobile != null ?
                new ObjectParameter("mobile", mobile) :
                new ObjectParameter("mobile", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_insert_raffel", nameParameter, emailParameter, mobileParameter);
        }
    
        public virtual ObjectResult<SP_PODEventRegistration_Result> SP_PODEventRegistration(string fullName, string email, string companyName, string passcode, string linkUrl)
        {
            var fullNameParameter = fullName != null ?
                new ObjectParameter("FullName", fullName) :
                new ObjectParameter("FullName", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var companyNameParameter = companyName != null ?
                new ObjectParameter("CompanyName", companyName) :
                new ObjectParameter("CompanyName", typeof(string));
    
            var passcodeParameter = passcode != null ?
                new ObjectParameter("Passcode", passcode) :
                new ObjectParameter("Passcode", typeof(string));
    
            var linkUrlParameter = linkUrl != null ?
                new ObjectParameter("LinkUrl", linkUrl) :
                new ObjectParameter("LinkUrl", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_PODEventRegistration_Result>("SP_PODEventRegistration", fullNameParameter, emailParameter, companyNameParameter, passcodeParameter, linkUrlParameter);
        }
    
        public virtual ObjectResult<sp_select_raffel_Result> sp_select_raffel()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_select_raffel_Result>("sp_select_raffel");
        }
    }
}
