//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEWAXP.Foundation.CustomDB.DRRGDataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DRRGEntities : DbContext
    {
        public DRRGEntities()
            : base("name=DRRGEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DRRG_ApplicationHistory> DRRG_ApplicationHistory { get; set; }
        public virtual DbSet<DRRG_ApplicationSession> DRRG_ApplicationSession { get; set; }
        public virtual DbSet<DRRG_EvaluatorLogin> DRRG_EvaluatorLogin { get; set; }
        public virtual DbSet<DRRG_Factory_Details> DRRG_Factory_Details { get; set; }
        public virtual DbSet<DRRG_Files> DRRG_Files { get; set; }
        public virtual DbSet<DRRG_InterfaceModule> DRRG_InterfaceModule { get; set; }
        public virtual DbSet<DRRG_InverterModule> DRRG_InverterModule { get; set; }
        public virtual DbSet<DRRG_InverterModule_AP> DRRG_InverterModule_AP { get; set; }
        public virtual DbSet<DRRG_InverterModule_MAP> DRRG_InverterModule_MAP { get; set; }
        public virtual DbSet<DRRG_InverterModule_RP> DRRG_InverterModule_RP { get; set; }
        public virtual DbSet<DRRG_Manufacturer_Details> DRRG_Manufacturer_Details { get; set; }
        public virtual DbSet<DRRG_PVModule_Nominal> DRRG_PVModule_Nominal { get; set; }
        public virtual DbSet<DRRG_Rejected> DRRG_Rejected { get; set; }
        public virtual DbSet<DRRG_UserLogin> DRRG_UserLogin { get; set; }
        public virtual DbSet<DRRG_UserSession> DRRG_UserSession { get; set; }
        public virtual DbSet<DRRG_PVMODULE> DRRG_PVMODULE { get; set; }
    
        public virtual int SP_DRRG_AdminLogin(string loginusername, ObjectParameter responseMessage, ObjectParameter sessionout)
        {
            var loginusernameParameter = loginusername != null ?
                new ObjectParameter("loginusername", loginusername) :
                new ObjectParameter("loginusername", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DRRG_AdminLogin", loginusernameParameter, responseMessage, sessionout);
        }
    
        public virtual int SP_DRRG_CheckAdminSession(string loginusername, string session, ObjectParameter responseMessage)
        {
            var loginusernameParameter = loginusername != null ?
                new ObjectParameter("loginusername", loginusername) :
                new ObjectParameter("loginusername", typeof(string));
    
            var sessionParameter = session != null ?
                new ObjectParameter("session", session) :
                new ObjectParameter("session", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DRRG_CheckAdminSession", loginusernameParameter, sessionParameter, responseMessage);
        }
    
        public virtual int SP_DRRG_CheckSession(string loginusername, string session, string manufactercode, ObjectParameter status, ObjectParameter responseMessage)
        {
            var loginusernameParameter = loginusername != null ?
                new ObjectParameter("loginusername", loginusername) :
                new ObjectParameter("loginusername", typeof(string));
    
            var sessionParameter = session != null ?
                new ObjectParameter("session", session) :
                new ObjectParameter("session", typeof(string));
    
            var manufactercodeParameter = manufactercode != null ?
                new ObjectParameter("manufactercode", manufactercode) :
                new ObjectParameter("manufactercode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DRRG_CheckSession", loginusernameParameter, sessionParameter, manufactercodeParameter, status, responseMessage);
        }
    
        public virtual int SP_DRRG_DashboardCount(ObjectParameter ltsubmitted, ObjectParameter ltupdated, ObjectParameter ltrejected, ObjectParameter equipmentcount)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DRRG_DashboardCount", ltsubmitted, ltupdated, ltrejected, equipmentcount);
        }
    
        public virtual int SP_DRRG_EvaluatorRegApproval(string refId, string useremail, ObjectParameter error)
        {
            var refIdParameter = refId != null ?
                new ObjectParameter("refId", refId) :
                new ObjectParameter("refId", typeof(string));
    
            var useremailParameter = useremail != null ?
                new ObjectParameter("useremail", useremail) :
                new ObjectParameter("useremail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DRRG_EvaluatorRegApproval", refIdParameter, useremailParameter, error);
        }
    
        public virtual ObjectResult<string> SP_DRRG_EvalutorLogin(string loginusername, ObjectParameter responseMessage, ObjectParameter sessionout, ObjectParameter evaluatorcode)
        {
            var loginusernameParameter = loginusername != null ?
                new ObjectParameter("loginusername", loginusername) :
                new ObjectParameter("loginusername", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_DRRG_EvalutorLogin", loginusernameParameter, responseMessage, sessionout, evaluatorcode);
        }
    
        public virtual int SP_DRRG_EvalutorRegistration(string loginusername, string name, string referenceid, ObjectParameter responseMessage)
        {
            var loginusernameParameter = loginusername != null ?
                new ObjectParameter("loginusername", loginusername) :
                new ObjectParameter("loginusername", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var referenceidParameter = referenceid != null ?
                new ObjectParameter("referenceid", referenceid) :
                new ObjectParameter("referenceid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DRRG_EvalutorRegistration", loginusernameParameter, nameParameter, referenceidParameter, responseMessage);
        }
    
        public virtual ObjectResult<SP_DRRG_GetApplicationDetailsById_Result> SP_DRRG_GetApplicationDetailsById(Nullable<long> id, Nullable<short> type)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(long));
    
            var typeParameter = type.HasValue ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(short));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DRRG_GetApplicationDetailsById_Result>("SP_DRRG_GetApplicationDetailsById", idParameter, typeParameter);
        }
    
        public virtual ObjectResult<SP_DRRG_GETEvaluatorBySchemaManager_Result> SP_DRRG_GETEvaluatorBySchemaManager()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DRRG_GETEvaluatorBySchemaManager_Result>("SP_DRRG_GETEvaluatorBySchemaManager");
        }
    
        public virtual ObjectResult<SP_DRRG_GETEvaluatorListBySchemaManager_Result> SP_DRRG_GETEvaluatorListBySchemaManager()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DRRG_GETEvaluatorListBySchemaManager_Result>("SP_DRRG_GETEvaluatorListBySchemaManager");
        }
    
        public virtual ObjectResult<SP_DRRG_GETFactorybyID_Result> SP_DRRG_GETFactorybyID(string manufacturercode)
        {
            var manufacturercodeParameter = manufacturercode != null ?
                new ObjectParameter("manufacturercode", manufacturercode) :
                new ObjectParameter("manufacturercode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DRRG_GETFactorybyID_Result>("SP_DRRG_GETFactorybyID", manufacturercodeParameter);
        }
    
        public virtual ObjectResult<SP_DRRG_GETFactorydetails_Result> SP_DRRG_GETFactorydetails(string manufacturercode, string useremail)
        {
            var manufacturercodeParameter = manufacturercode != null ?
                new ObjectParameter("manufacturercode", manufacturercode) :
                new ObjectParameter("manufacturercode", typeof(string));
    
            var useremailParameter = useremail != null ?
                new ObjectParameter("useremail", useremail) :
                new ObjectParameter("useremail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DRRG_GETFactorydetails_Result>("SP_DRRG_GETFactorydetails", manufacturercodeParameter, useremailParameter);
        }
    
        public virtual ObjectResult<SP_DRRG_GETFilesbyfileID_Result> SP_DRRG_GETFilesbyfileID(string id, string manufacturecode)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            var manufacturecodeParameter = manufacturecode != null ?
                new ObjectParameter("manufacturecode", manufacturecode) :
                new ObjectParameter("manufacturecode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DRRG_GETFilesbyfileID_Result>("SP_DRRG_GETFilesbyfileID", idParameter, manufacturecodeParameter);
        }
    
        public virtual ObjectResult<SP_DRRG_GETFilesbyfileIDAdmin_Result> SP_DRRG_GETFilesbyfileIDAdmin(string id)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DRRG_GETFilesbyfileIDAdmin_Result>("SP_DRRG_GETFilesbyfileIDAdmin", idParameter);
        }
    
        public virtual ObjectResult<SP_DRRG_GETFilesbyID_Result> SP_DRRG_GETFilesbyID(string id, string manufacturercode)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            var manufacturercodeParameter = manufacturercode != null ?
                new ObjectParameter("manufacturercode", manufacturercode) :
                new ObjectParameter("manufacturercode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DRRG_GETFilesbyID_Result>("SP_DRRG_GETFilesbyID", idParameter, manufacturercodeParameter);
        }
    
        public virtual ObjectResult<SP_DRRG_GETFilesbyIDAdmin_Result> SP_DRRG_GETFilesbyIDAdmin(string id)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DRRG_GETFilesbyIDAdmin_Result>("SP_DRRG_GETFilesbyIDAdmin", idParameter);
        }
    
        public virtual ObjectResult<SP_DRRG_GETFilteredInterfaceModule_Result> SP_DRRG_GETFilteredInterfaceModule(string manufacturercode, string useremail)
        {
            var manufacturercodeParameter = manufacturercode != null ?
                new ObjectParameter("manufacturercode", manufacturercode) :
                new ObjectParameter("manufacturercode", typeof(string));
    
            var useremailParameter = useremail != null ?
                new ObjectParameter("useremail", useremail) :
                new ObjectParameter("useremail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DRRG_GETFilteredInterfaceModule_Result>("SP_DRRG_GETFilteredInterfaceModule", manufacturercodeParameter, useremailParameter);
        }
    
        public virtual ObjectResult<SP_DRRG_GETFilteredInterfaceModulebyID_Result> SP_DRRG_GETFilteredInterfaceModulebyID(string manufacturercode, string id, string useremail)
        {
            var manufacturercodeParameter = manufacturercode != null ?
                new ObjectParameter("manufacturercode", manufacturercode) :
                new ObjectParameter("manufacturercode", typeof(string));
    
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            var useremailParameter = useremail != null ?
                new ObjectParameter("useremail", useremail) :
                new ObjectParameter("useremail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DRRG_GETFilteredInterfaceModulebyID_Result>("SP_DRRG_GETFilteredInterfaceModulebyID", manufacturercodeParameter, idParameter, useremailParameter);
        }
    
        public virtual ObjectResult<SP_DRRG_GETFilteredInverterModule_Result> SP_DRRG_GETFilteredInverterModule(string manufacturercode, string useremail)
        {
            var manufacturercodeParameter = manufacturercode != null ?
                new ObjectParameter("manufacturercode", manufacturercode) :
                new ObjectParameter("manufacturercode", typeof(string));
    
            var useremailParameter = useremail != null ?
                new ObjectParameter("useremail", useremail) :
                new ObjectParameter("useremail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DRRG_GETFilteredInverterModule_Result>("SP_DRRG_GETFilteredInverterModule", manufacturercodeParameter, useremailParameter);
        }
    
        public virtual ObjectResult<SP_DRRG_GETFilteredInverterModulebyID_Result> SP_DRRG_GETFilteredInverterModulebyID(string manufacturercode, string id, string useremail)
        {
            var manufacturercodeParameter = manufacturercode != null ?
                new ObjectParameter("manufacturercode", manufacturercode) :
                new ObjectParameter("manufacturercode", typeof(string));
    
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            var useremailParameter = useremail != null ?
                new ObjectParameter("useremail", useremail) :
                new ObjectParameter("useremail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DRRG_GETFilteredInverterModulebyID_Result>("SP_DRRG_GETFilteredInverterModulebyID", manufacturercodeParameter, idParameter, useremailParameter);
        }
    
        public virtual ObjectResult<SP_DRRG_GETFilteredPVModule_Result> SP_DRRG_GETFilteredPVModule(string manufacturercode, string useremail)
        {
            var manufacturercodeParameter = manufacturercode != null ?
                new ObjectParameter("manufacturercode", manufacturercode) :
                new ObjectParameter("manufacturercode", typeof(string));
    
            var useremailParameter = useremail != null ?
                new ObjectParameter("useremail", useremail) :
                new ObjectParameter("useremail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DRRG_GETFilteredPVModule_Result>("SP_DRRG_GETFilteredPVModule", manufacturercodeParameter, useremailParameter);
        }
    
        public virtual ObjectResult<SP_DRRG_GETFilteredPVModulebyID_Result> SP_DRRG_GETFilteredPVModulebyID(string manufacturercode, string id, string useremail)
        {
            var manufacturercodeParameter = manufacturercode != null ?
                new ObjectParameter("manufacturercode", manufacturercode) :
                new ObjectParameter("manufacturercode", typeof(string));
    
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            var useremailParameter = useremail != null ?
                new ObjectParameter("useremail", useremail) :
                new ObjectParameter("useremail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DRRG_GETFilteredPVModulebyID_Result>("SP_DRRG_GETFilteredPVModulebyID", manufacturercodeParameter, idParameter, useremailParameter);
        }
    
        public virtual ObjectResult<SP_DRRG_GETInterfaceModuleByManuId_Result> SP_DRRG_GETInterfaceModuleByManuId(string manufacturercode)
        {
            var manufacturercodeParameter = manufacturercode != null ?
                new ObjectParameter("manufacturercode", manufacturercode) :
                new ObjectParameter("manufacturercode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DRRG_GETInterfaceModuleByManuId_Result>("SP_DRRG_GETInterfaceModuleByManuId", manufacturercodeParameter);
        }
    
        public virtual ObjectResult<SP_DRRG_GETInverterModuleByManuId_Result> SP_DRRG_GETInverterModuleByManuId(string manufacturercode)
        {
            var manufacturercodeParameter = manufacturercode != null ?
                new ObjectParameter("manufacturercode", manufacturercode) :
                new ObjectParameter("manufacturercode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DRRG_GETInverterModuleByManuId_Result>("SP_DRRG_GETInverterModuleByManuId", manufacturercodeParameter);
        }
    
        public virtual ObjectResult<SP_DRRG_GETManufacturerbyID_Result> SP_DRRG_GETManufacturerbyID(string manufacturercode, string status)
        {
            var manufacturercodeParameter = manufacturercode != null ?
                new ObjectParameter("manufacturercode", manufacturercode) :
                new ObjectParameter("manufacturercode", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DRRG_GETManufacturerbyID_Result>("SP_DRRG_GETManufacturerbyID", manufacturercodeParameter, statusParameter);
        }
    
        public virtual ObjectResult<SP_DRRG_GETManufacturerdetails_Result> SP_DRRG_GETManufacturerdetails(string manufacturercode, string useremail)
        {
            var manufacturercodeParameter = manufacturercode != null ?
                new ObjectParameter("manufacturercode", manufacturercode) :
                new ObjectParameter("manufacturercode", typeof(string));
    
            var useremailParameter = useremail != null ?
                new ObjectParameter("useremail", useremail) :
                new ObjectParameter("useremail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DRRG_GETManufacturerdetails_Result>("SP_DRRG_GETManufacturerdetails", manufacturercodeParameter, useremailParameter);
        }
    
        public virtual ObjectResult<SP_DRRG_GETManuRejectedComments_Result> SP_DRRG_GETManuRejectedComments(string id)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DRRG_GETManuRejectedComments_Result>("SP_DRRG_GETManuRejectedComments", idParameter);
        }
    
        public virtual ObjectResult<SP_DRRG_GETManuRejectedFilesbyIDAdmin_Result> SP_DRRG_GETManuRejectedFilesbyIDAdmin(string id)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DRRG_GETManuRejectedFilesbyIDAdmin_Result>("SP_DRRG_GETManuRejectedFilesbyIDAdmin", idParameter);
        }
    
        public virtual ObjectResult<SP_DRRG_GETModules_Result> SP_DRRG_GETModules(string manufacturercode, string useremail)
        {
            var manufacturercodeParameter = manufacturercode != null ?
                new ObjectParameter("manufacturercode", manufacturercode) :
                new ObjectParameter("manufacturercode", typeof(string));
    
            var useremailParameter = useremail != null ?
                new ObjectParameter("useremail", useremail) :
                new ObjectParameter("useremail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DRRG_GETModules_Result>("SP_DRRG_GETModules", manufacturercodeParameter, useremailParameter);
        }
    
        public virtual ObjectResult<SP_DRRG_GETModulesByAdmin_Result> SP_DRRG_GETModulesByAdmin()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DRRG_GETModulesByAdmin_Result>("SP_DRRG_GETModulesByAdmin");
        }
    
        public virtual ObjectResult<SP_DRRG_GETModulesByAdminLogs_Result> SP_DRRG_GETModulesByAdminLogs()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DRRG_GETModulesByAdminLogs_Result>("SP_DRRG_GETModulesByAdminLogs");
        }
    
        public virtual ObjectResult<SP_DRRG_GETModulesByManuId_Result> SP_DRRG_GETModulesByManuId(string manufacturercode, string type)
        {
            var manufacturercodeParameter = manufacturercode != null ?
                new ObjectParameter("manufacturercode", manufacturercode) :
                new ObjectParameter("manufacturercode", typeof(string));
    
            var typeParameter = type != null ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DRRG_GETModulesByManuId_Result>("SP_DRRG_GETModulesByManuId", manufacturercodeParameter, typeParameter);
        }
    
        public virtual ObjectResult<SP_DRRG_GETModulesBySchemaManager_Result> SP_DRRG_GETModulesBySchemaManager()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DRRG_GETModulesBySchemaManager_Result>("SP_DRRG_GETModulesBySchemaManager");
        }
    
        public virtual ObjectResult<SP_DRRG_GETPVModuleByManuId_Result> SP_DRRG_GETPVModuleByManuId(string manufacturercode)
        {
            var manufacturercodeParameter = manufacturercode != null ?
                new ObjectParameter("manufacturercode", manufacturercode) :
                new ObjectParameter("manufacturercode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DRRG_GETPVModuleByManuId_Result>("SP_DRRG_GETPVModuleByManuId", manufacturercodeParameter);
        }
    
        public virtual ObjectResult<SP_DRRG_GetRejectedApplicationModules_Result> SP_DRRG_GetRejectedApplicationModules(string manufacturercode, string useremail, Nullable<short> type)
        {
            var manufacturercodeParameter = manufacturercode != null ?
                new ObjectParameter("manufacturercode", manufacturercode) :
                new ObjectParameter("manufacturercode", typeof(string));
    
            var useremailParameter = useremail != null ?
                new ObjectParameter("useremail", useremail) :
                new ObjectParameter("useremail", typeof(string));
    
            var typeParameter = type.HasValue ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(short));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DRRG_GetRejectedApplicationModules_Result>("SP_DRRG_GetRejectedApplicationModules", manufacturercodeParameter, useremailParameter, typeParameter);
        }
    
        public virtual ObjectResult<SP_DRRG_GetRejectedModulesBySchemaManager_Result> SP_DRRG_GetRejectedModulesBySchemaManager()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DRRG_GetRejectedModulesBySchemaManager_Result>("SP_DRRG_GetRejectedModulesBySchemaManager");
        }
    
        public virtual ObjectResult<SP_DRRG_GETSubmittedManufacturer_Result> SP_DRRG_GETSubmittedManufacturer(string status)
        {
            var statusParameter = status != null ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DRRG_GETSubmittedManufacturer_Result>("SP_DRRG_GETSubmittedManufacturer", statusParameter);
        }
    
        public virtual int SP_DRRG_InsertAuthorizationLetter(string useremail, string manufacturecode, ObjectParameter error)
        {
            var useremailParameter = useremail != null ?
                new ObjectParameter("useremail", useremail) :
                new ObjectParameter("useremail", typeof(string));
    
            var manufacturecodeParameter = manufacturecode != null ?
                new ObjectParameter("manufacturecode", manufacturecode) :
                new ObjectParameter("manufacturecode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DRRG_InsertAuthorizationLetter", useremailParameter, manufacturecodeParameter, error);
        }
    
        public virtual int SP_DRRG_InsertinterfaceModule(Nullable<int> updateId, string useremail, ObjectParameter error)
        {
            var updateIdParameter = updateId.HasValue ?
                new ObjectParameter("updateId", updateId) :
                new ObjectParameter("updateId", typeof(int));
    
            var useremailParameter = useremail != null ?
                new ObjectParameter("useremail", useremail) :
                new ObjectParameter("useremail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DRRG_InsertinterfaceModule", updateIdParameter, useremailParameter, error);
        }
    
        public virtual int SP_DRRG_InsertinverterModule(string useremail, ObjectParameter error)
        {
            var useremailParameter = useremail != null ?
                new ObjectParameter("useremail", useremail) :
                new ObjectParameter("useremail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DRRG_InsertinverterModule", useremailParameter, error);
        }
    
        public virtual int SP_DRRG_InsertManufacturer(string useremail, ObjectParameter error)
        {
            var useremailParameter = useremail != null ?
                new ObjectParameter("useremail", useremail) :
                new ObjectParameter("useremail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DRRG_InsertManufacturer", useremailParameter, error);
        }
    
        public virtual int SP_DRRG_Insertpasswordlink(string loginusername, string link, ObjectParameter responseMessage)
        {
            var loginusernameParameter = loginusername != null ?
                new ObjectParameter("loginusername", loginusername) :
                new ObjectParameter("loginusername", typeof(string));
    
            var linkParameter = link != null ?
                new ObjectParameter("link", link) :
                new ObjectParameter("link", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DRRG_Insertpasswordlink", loginusernameParameter, linkParameter, responseMessage);
        }
    
        public virtual int SP_DRRG_InsertPVModule(string referenceID, Nullable<int> updateId, string useremail, ObjectParameter error)
        {
            var referenceIDParameter = referenceID != null ?
                new ObjectParameter("referenceID", referenceID) :
                new ObjectParameter("referenceID", typeof(string));
    
            var updateIdParameter = updateId.HasValue ?
                new ObjectParameter("updateId", updateId) :
                new ObjectParameter("updateId", typeof(int));
    
            var useremailParameter = useremail != null ?
                new ObjectParameter("useremail", useremail) :
                new ObjectParameter("useremail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DRRG_InsertPVModule", referenceIDParameter, updateIdParameter, useremailParameter, error);
        }
    
        public virtual int SP_DRRG_Login(string loginusername, string password, ObjectParameter responseMessage, ObjectParameter sessionout, ObjectParameter name, ObjectParameter manufactercode)
        {
            var loginusernameParameter = loginusername != null ?
                new ObjectParameter("loginusername", loginusername) :
                new ObjectParameter("loginusername", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DRRG_Login", loginusernameParameter, passwordParameter, responseMessage, sessionout, name, manufactercode);
        }
    
        public virtual int SP_DRRG_Logout(string loginusername, string session, ObjectParameter responseMessage)
        {
            var loginusernameParameter = loginusername != null ?
                new ObjectParameter("loginusername", loginusername) :
                new ObjectParameter("loginusername", typeof(string));
    
            var sessionParameter = session != null ?
                new ObjectParameter("session", session) :
                new ObjectParameter("session", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DRRG_Logout", loginusernameParameter, sessionParameter, responseMessage);
        }
    
        public virtual int SP_DRRG_ManufacturerApproval(string useremail, string manufacturecode, ObjectParameter manufacturername, ObjectParameter manufactureremail, ObjectParameter error)
        {
            var useremailParameter = useremail != null ?
                new ObjectParameter("useremail", useremail) :
                new ObjectParameter("useremail", typeof(string));
    
            var manufacturecodeParameter = manufacturecode != null ?
                new ObjectParameter("manufacturecode", manufacturecode) :
                new ObjectParameter("manufacturecode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DRRG_ManufacturerApproval", useremailParameter, manufacturecodeParameter, manufacturername, manufactureremail, error);
        }
    
        public virtual int SP_DRRG_ManufacturerRejection(string useremail, string rejectedreason, string rejectedfileid, string manufacturecode, ObjectParameter manufacturername, ObjectParameter manufactureremail, ObjectParameter error)
        {
            var useremailParameter = useremail != null ?
                new ObjectParameter("useremail", useremail) :
                new ObjectParameter("useremail", typeof(string));
    
            var rejectedreasonParameter = rejectedreason != null ?
                new ObjectParameter("rejectedreason", rejectedreason) :
                new ObjectParameter("rejectedreason", typeof(string));
    
            var rejectedfileidParameter = rejectedfileid != null ?
                new ObjectParameter("rejectedfileid", rejectedfileid) :
                new ObjectParameter("rejectedfileid", typeof(string));
    
            var manufacturecodeParameter = manufacturecode != null ?
                new ObjectParameter("manufacturecode", manufacturecode) :
                new ObjectParameter("manufacturecode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DRRG_ManufacturerRejection", useremailParameter, rejectedreasonParameter, rejectedfileidParameter, manufacturecodeParameter, manufacturername, manufactureremail, error);
        }
    
        public virtual int SP_DRRG_PVInterfaceApproval(string useremail, string pvinterfacecode, string pvtestmethod, ObjectParameter error)
        {
            var useremailParameter = useremail != null ?
                new ObjectParameter("useremail", useremail) :
                new ObjectParameter("useremail", typeof(string));
    
            var pvinterfacecodeParameter = pvinterfacecode != null ?
                new ObjectParameter("pvinterfacecode", pvinterfacecode) :
                new ObjectParameter("pvinterfacecode", typeof(string));
    
            var pvtestmethodParameter = pvtestmethod != null ?
                new ObjectParameter("pvtestmethod", pvtestmethod) :
                new ObjectParameter("pvtestmethod", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DRRG_PVInterfaceApproval", useremailParameter, pvinterfacecodeParameter, pvtestmethodParameter, error);
        }
    
        public virtual int SP_DRRG_PVInterfaceRejection(string useremail, string rejectedreason, string rejectedfileid, string pvcode, ObjectParameter pvmodelname, ObjectParameter pvusername, ObjectParameter pvuseremail, ObjectParameter error)
        {
            var useremailParameter = useremail != null ?
                new ObjectParameter("useremail", useremail) :
                new ObjectParameter("useremail", typeof(string));
    
            var rejectedreasonParameter = rejectedreason != null ?
                new ObjectParameter("rejectedreason", rejectedreason) :
                new ObjectParameter("rejectedreason", typeof(string));
    
            var rejectedfileidParameter = rejectedfileid != null ?
                new ObjectParameter("rejectedfileid", rejectedfileid) :
                new ObjectParameter("rejectedfileid", typeof(string));
    
            var pvcodeParameter = pvcode != null ?
                new ObjectParameter("pvcode", pvcode) :
                new ObjectParameter("pvcode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DRRG_PVInterfaceRejection", useremailParameter, rejectedreasonParameter, rejectedfileidParameter, pvcodeParameter, pvmodelname, pvusername, pvuseremail, error);
        }
    
        public virtual int SP_DRRG_PVInverterApproval(string useremail, string pvinvertercode, string pvtestmethod, ObjectParameter error)
        {
            var useremailParameter = useremail != null ?
                new ObjectParameter("useremail", useremail) :
                new ObjectParameter("useremail", typeof(string));
    
            var pvinvertercodeParameter = pvinvertercode != null ?
                new ObjectParameter("pvinvertercode", pvinvertercode) :
                new ObjectParameter("pvinvertercode", typeof(string));
    
            var pvtestmethodParameter = pvtestmethod != null ?
                new ObjectParameter("pvtestmethod", pvtestmethod) :
                new ObjectParameter("pvtestmethod", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DRRG_PVInverterApproval", useremailParameter, pvinvertercodeParameter, pvtestmethodParameter, error);
        }
    
        public virtual int SP_DRRG_PVInverterRejection(string useremail, string rejectedreason, string rejectedfileid, string pvcode, ObjectParameter pvmodelname, ObjectParameter pvusername, ObjectParameter pvuseremail, ObjectParameter error)
        {
            var useremailParameter = useremail != null ?
                new ObjectParameter("useremail", useremail) :
                new ObjectParameter("useremail", typeof(string));
    
            var rejectedreasonParameter = rejectedreason != null ?
                new ObjectParameter("rejectedreason", rejectedreason) :
                new ObjectParameter("rejectedreason", typeof(string));
    
            var rejectedfileidParameter = rejectedfileid != null ?
                new ObjectParameter("rejectedfileid", rejectedfileid) :
                new ObjectParameter("rejectedfileid", typeof(string));
    
            var pvcodeParameter = pvcode != null ?
                new ObjectParameter("pvcode", pvcode) :
                new ObjectParameter("pvcode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DRRG_PVInverterRejection", useremailParameter, rejectedreasonParameter, rejectedfileidParameter, pvcodeParameter, pvmodelname, pvusername, pvuseremail, error);
        }
    
        public virtual int SP_DRRG_PVModuleApproval(string useremail, string pvcode, string pvtestmethod, ObjectParameter error)
        {
            var useremailParameter = useremail != null ?
                new ObjectParameter("useremail", useremail) :
                new ObjectParameter("useremail", typeof(string));
    
            var pvcodeParameter = pvcode != null ?
                new ObjectParameter("pvcode", pvcode) :
                new ObjectParameter("pvcode", typeof(string));
    
            var pvtestmethodParameter = pvtestmethod != null ?
                new ObjectParameter("pvtestmethod", pvtestmethod) :
                new ObjectParameter("pvtestmethod", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DRRG_PVModuleApproval", useremailParameter, pvcodeParameter, pvtestmethodParameter, error);
        }
    
        public virtual int SP_DRRG_PVModuleRejection(string useremail, string rejectedreason, string rejectedfileid, string pvcode, ObjectParameter pvmodelname, ObjectParameter pvusername, ObjectParameter pvuseremail, ObjectParameter error)
        {
            var useremailParameter = useremail != null ?
                new ObjectParameter("useremail", useremail) :
                new ObjectParameter("useremail", typeof(string));
    
            var rejectedreasonParameter = rejectedreason != null ?
                new ObjectParameter("rejectedreason", rejectedreason) :
                new ObjectParameter("rejectedreason", typeof(string));
    
            var rejectedfileidParameter = rejectedfileid != null ?
                new ObjectParameter("rejectedfileid", rejectedfileid) :
                new ObjectParameter("rejectedfileid", typeof(string));
    
            var pvcodeParameter = pvcode != null ?
                new ObjectParameter("pvcode", pvcode) :
                new ObjectParameter("pvcode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DRRG_PVModuleRejection", useremailParameter, rejectedreasonParameter, rejectedfileidParameter, pvcodeParameter, pvmodelname, pvusername, pvuseremail, error);
        }
    
        public virtual int SP_DRRG_SchemaMgr_EvaluatorRegistration_Rejection(string useremail, string referenceid, string rejectedreason, string rejectedfileid, ObjectParameter error)
        {
            var useremailParameter = useremail != null ?
                new ObjectParameter("useremail", useremail) :
                new ObjectParameter("useremail", typeof(string));
    
            var referenceidParameter = referenceid != null ?
                new ObjectParameter("referenceid", referenceid) :
                new ObjectParameter("referenceid", typeof(string));
    
            var rejectedreasonParameter = rejectedreason != null ?
                new ObjectParameter("rejectedreason", rejectedreason) :
                new ObjectParameter("rejectedreason", typeof(string));
    
            var rejectedfileidParameter = rejectedfileid != null ?
                new ObjectParameter("rejectedfileid", rejectedfileid) :
                new ObjectParameter("rejectedfileid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DRRG_SchemaMgr_EvaluatorRegistration_Rejection", useremailParameter, referenceidParameter, rejectedreasonParameter, rejectedfileidParameter, error);
        }
    
        public virtual ObjectResult<SP_DRRG_SchemaMgr_GetReports_Result> SP_DRRG_SchemaMgr_GetReports(string fromDate, string toDate)
        {
            var fromDateParameter = fromDate != null ?
                new ObjectParameter("fromDate", fromDate) :
                new ObjectParameter("fromDate", typeof(string));
    
            var toDateParameter = toDate != null ?
                new ObjectParameter("toDate", toDate) :
                new ObjectParameter("toDate", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DRRG_SchemaMgr_GetReports_Result>("SP_DRRG_SchemaMgr_GetReports", fromDateParameter, toDateParameter);
        }
    
        public virtual int SP_DRRG_SchemaMgr_PVInterfaceApproval(string useremail, string pvinterfacecode, string pvtestmethod, ObjectParameter error)
        {
            var useremailParameter = useremail != null ?
                new ObjectParameter("useremail", useremail) :
                new ObjectParameter("useremail", typeof(string));
    
            var pvinterfacecodeParameter = pvinterfacecode != null ?
                new ObjectParameter("pvinterfacecode", pvinterfacecode) :
                new ObjectParameter("pvinterfacecode", typeof(string));
    
            var pvtestmethodParameter = pvtestmethod != null ?
                new ObjectParameter("pvtestmethod", pvtestmethod) :
                new ObjectParameter("pvtestmethod", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DRRG_SchemaMgr_PVInterfaceApproval", useremailParameter, pvinterfacecodeParameter, pvtestmethodParameter, error);
        }
    
        public virtual int SP_DRRG_SchemaMgr_PVInterfaceRejection(string useremail, string rejectedreason, string rejectedfileid, string pvcode, ObjectParameter pvmodelname, ObjectParameter pvusername, ObjectParameter pvuseremail, ObjectParameter error)
        {
            var useremailParameter = useremail != null ?
                new ObjectParameter("useremail", useremail) :
                new ObjectParameter("useremail", typeof(string));
    
            var rejectedreasonParameter = rejectedreason != null ?
                new ObjectParameter("rejectedreason", rejectedreason) :
                new ObjectParameter("rejectedreason", typeof(string));
    
            var rejectedfileidParameter = rejectedfileid != null ?
                new ObjectParameter("rejectedfileid", rejectedfileid) :
                new ObjectParameter("rejectedfileid", typeof(string));
    
            var pvcodeParameter = pvcode != null ?
                new ObjectParameter("pvcode", pvcode) :
                new ObjectParameter("pvcode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DRRG_SchemaMgr_PVInterfaceRejection", useremailParameter, rejectedreasonParameter, rejectedfileidParameter, pvcodeParameter, pvmodelname, pvusername, pvuseremail, error);
        }
    
        public virtual int SP_DRRG_SchemaMgr_PVInverterApproval(string useremail, string pvinvertercode, string pvtestmethod, ObjectParameter error)
        {
            var useremailParameter = useremail != null ?
                new ObjectParameter("useremail", useremail) :
                new ObjectParameter("useremail", typeof(string));
    
            var pvinvertercodeParameter = pvinvertercode != null ?
                new ObjectParameter("pvinvertercode", pvinvertercode) :
                new ObjectParameter("pvinvertercode", typeof(string));
    
            var pvtestmethodParameter = pvtestmethod != null ?
                new ObjectParameter("pvtestmethod", pvtestmethod) :
                new ObjectParameter("pvtestmethod", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DRRG_SchemaMgr_PVInverterApproval", useremailParameter, pvinvertercodeParameter, pvtestmethodParameter, error);
        }
    
        public virtual int SP_DRRG_SchemaMgr_PVInverterRejection(string useremail, string rejectedreason, string rejectedfileid, string pvcode, ObjectParameter pvmodelname, ObjectParameter pvusername, ObjectParameter pvuseremail, ObjectParameter error)
        {
            var useremailParameter = useremail != null ?
                new ObjectParameter("useremail", useremail) :
                new ObjectParameter("useremail", typeof(string));
    
            var rejectedreasonParameter = rejectedreason != null ?
                new ObjectParameter("rejectedreason", rejectedreason) :
                new ObjectParameter("rejectedreason", typeof(string));
    
            var rejectedfileidParameter = rejectedfileid != null ?
                new ObjectParameter("rejectedfileid", rejectedfileid) :
                new ObjectParameter("rejectedfileid", typeof(string));
    
            var pvcodeParameter = pvcode != null ?
                new ObjectParameter("pvcode", pvcode) :
                new ObjectParameter("pvcode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DRRG_SchemaMgr_PVInverterRejection", useremailParameter, rejectedreasonParameter, rejectedfileidParameter, pvcodeParameter, pvmodelname, pvusername, pvuseremail, error);
        }
    
        public virtual int SP_DRRG_SchemaMgr_PVModuleApproval(string useremail, string pvcode, string pvtestmethod, ObjectParameter error)
        {
            var useremailParameter = useremail != null ?
                new ObjectParameter("useremail", useremail) :
                new ObjectParameter("useremail", typeof(string));
    
            var pvcodeParameter = pvcode != null ?
                new ObjectParameter("pvcode", pvcode) :
                new ObjectParameter("pvcode", typeof(string));
    
            var pvtestmethodParameter = pvtestmethod != null ?
                new ObjectParameter("pvtestmethod", pvtestmethod) :
                new ObjectParameter("pvtestmethod", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DRRG_SchemaMgr_PVModuleApproval", useremailParameter, pvcodeParameter, pvtestmethodParameter, error);
        }
    
        public virtual int SP_DRRG_SchemaMgr_PVModuleRejection(string useremail, string rejectedreason, string rejectedfileid, string pvcode, ObjectParameter pvmodelname, ObjectParameter pvusername, ObjectParameter pvuseremail, ObjectParameter error)
        {
            var useremailParameter = useremail != null ?
                new ObjectParameter("useremail", useremail) :
                new ObjectParameter("useremail", typeof(string));
    
            var rejectedreasonParameter = rejectedreason != null ?
                new ObjectParameter("rejectedreason", rejectedreason) :
                new ObjectParameter("rejectedreason", typeof(string));
    
            var rejectedfileidParameter = rejectedfileid != null ?
                new ObjectParameter("rejectedfileid", rejectedfileid) :
                new ObjectParameter("rejectedfileid", typeof(string));
    
            var pvcodeParameter = pvcode != null ?
                new ObjectParameter("pvcode", pvcode) :
                new ObjectParameter("pvcode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DRRG_SchemaMgr_PVModuleRejection", useremailParameter, rejectedreasonParameter, rejectedfileidParameter, pvcodeParameter, pvmodelname, pvusername, pvuseremail, error);
        }
    
        public virtual int SP_DRRG_SetNewPassword(string loginusername, string password, ObjectParameter responseMessage)
        {
            var loginusernameParameter = loginusername != null ?
                new ObjectParameter("loginusername", loginusername) :
                new ObjectParameter("loginusername", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DRRG_SetNewPassword", loginusernameParameter, passwordParameter, responseMessage);
        }
    
        public virtual int SP_DRRG_UpdateManufacturer(string useremail, string manufacturecode, ObjectParameter error)
        {
            var useremailParameter = useremail != null ?
                new ObjectParameter("useremail", useremail) :
                new ObjectParameter("useremail", typeof(string));
    
            var manufacturecodeParameter = manufacturecode != null ?
                new ObjectParameter("manufacturecode", manufacturecode) :
                new ObjectParameter("manufacturecode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DRRG_UpdateManufacturer", useremailParameter, manufacturecodeParameter, error);
        }
    
        public virtual int SP_DRRG_UserCheck(string loginusername, string link, ObjectParameter responseMessage)
        {
            var loginusernameParameter = loginusername != null ?
                new ObjectParameter("loginusername", loginusername) :
                new ObjectParameter("loginusername", typeof(string));
    
            var linkParameter = link != null ?
                new ObjectParameter("link", link) :
                new ObjectParameter("link", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DRRG_UserCheck", loginusernameParameter, linkParameter, responseMessage);
        }
    
        public virtual int SP_DRRG_Userdetails(string loginusername, string manufactercode, ObjectParameter firstname, ObjectParameter lastname, ObjectParameter manufacturername, ObjectParameter logofile, ObjectParameter logofileName, ObjectParameter logoContentType, ObjectParameter logoExtension)
        {
            var loginusernameParameter = loginusername != null ?
                new ObjectParameter("loginusername", loginusername) :
                new ObjectParameter("loginusername", typeof(string));
    
            var manufactercodeParameter = manufactercode != null ?
                new ObjectParameter("manufactercode", manufactercode) :
                new ObjectParameter("manufactercode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DRRG_Userdetails", loginusernameParameter, manufactercodeParameter, firstname, lastname, manufacturername, logofile, logofileName, logoContentType, logoExtension);
        }
    
        public virtual int DRRG_GetUserDetail_ByEmail(string username, ObjectParameter fullname)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DRRG_GetUserDetail_ByEmail", usernameParameter, fullname);
        }
    }
}
