//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEWAXP.Foundation.CustomDB.DRRGDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DRRG_ApplicationSession
    {
        public long Id { get; set; }
        public string ReferenceId { get; set; }
        public string SessionId { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
