//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEWAXP.Foundation.CustomDB.DRRGDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DRRG_InterfaceModule
    {
        public long id { get; set; }
        public string Interface_ID { get; set; }
        public string Parent_IP_ID { get; set; }
        public string Manufacturer_Code { get; set; }
        public string Model_Name { get; set; }
        public string Application { get; set; }
        public string CommunicationProtocol { get; set; }
        public string Compliance { get; set; }
        public string Salt_Mist_Test_Method { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string Session { get; set; }
        public string Userid { get; set; }
        public string Status { get; set; }
        public string Reviewed_By { get; set; }
        public string Approved_By { get; set; }
        public string Published_By { get; set; }
    }
}
