//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEWAXP.Foundation.CustomDB.DRRGDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DRRG_UserSession
    {
        public long id { get; set; }
        public string userid { get; set; }
        public string sessionid { get; set; }
        public System.DateTime fromtime { get; set; }
        public System.DateTime totime { get; set; }
    }
}
