//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEWAXP.Foundation.CustomDB.DRRGDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DRRG_Manufacturer_Details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DRRG_Manufacturer_Details()
        {
            this.DRRG_Factory_Details = new HashSet<DRRG_Factory_Details>();
        }
    
        public long Manufacturer_ID { get; set; }
        public string Manufacturer_Name { get; set; }
        public string Brand_Name { get; set; }
        public string Manufacturer_Country { get; set; }
        public string Corporate_Email { get; set; }
        public string Corporate_Phone_Number { get; set; }
        public string Corporate_Phone_Code { get; set; }
        public string Corporate_Fax_Number { get; set; }
        public string Corporate_Fax_Code { get; set; }
        public string Website { get; set; }
        public bool Local_Representative { get; set; }
        public string Company_Full_Name { get; set; }
        public string User_First_Name { get; set; }
        public string User_Last_Name { get; set; }
        public string User_Gender { get; set; }
        public string User_Nationality { get; set; }
        public string User_Designation { get; set; }
        public string User_Mobile_Number { get; set; }
        public string User_Mobile_Code { get; set; }
        public string User_Email_Address { get; set; }
        public bool Enabled { get; set; }
        public string Manufacturer_Code { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string Status { get; set; }
        public string Reviewed_By { get; set; }
        public string Approved_By { get; set; }
        public string Published_By { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DRRG_Factory_Details> DRRG_Factory_Details { get; set; }
    }
}
