//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEWAXP.Foundation.CustomDB.DRRGDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DRRG_UserLogin
    {
        public long ID { get; set; }
        public string Login_username { get; set; }
        public string Name { get; set; }
        public byte[] Password { get; set; }
        public string salt { get; set; }
        public string Manufacturer_Code { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string Status { get; set; }
        public string Reviewed_By { get; set; }
        public string Approved_By { get; set; }
        public string Published_By { get; set; }
        public Nullable<bool> PasswordExists { get; set; }
        public string Link { get; set; }
    }
}
