//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEWAXP.Foundation.CustomDB.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmiratiEventRegistration
    {
        public System.Guid id { get; set; }
        public string name { get; set; }
        public string emailid { get; set; }
        public string designation { get; set; }
        public string howtoattend { get; set; }
        public string prno { get; set; }
        public bool tc { get; set; }
        public bool hasvaccine { get; set; }
        public bool hasrtpcr { get; set; }
        public byte[] vaccinefile { get; set; }
        public string vaccinefilename { get; set; }
        public System.DateTime createddatetime { get; set; }
    }
}
