//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEWAXP.Foundation.CustomDB.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventRegistration
    {
        public System.Guid ID { get; set; }
        public string FullName { get; set; }
        public string CompanyName { get; set; }
        public string Country { get; set; }
        public string Designation { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string EventCode { get; set; }
        public string SessionName { get; set; }
        public Nullable<bool> Verified { get; set; }
        public string Institution { get; set; }
        public string LinkUrl { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> Attendance { get; set; }
        public Nullable<bool> Sent { get; set; }
    }
}
