//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEWAXP.Foundation.CustomDB.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class raffel
    {
        public int id { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string mobile { get; set; }
        public System.DateTime created_at { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    }
}
