//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEWAXP.Foundation.CustomDB.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebsiteSearchFeedback
    {
        public int SearchID { get; set; }
        public System.DateTime SearchDate { get; set; }
        public string SearchTerm { get; set; }
        public bool DidYouFind { get; set; }
        public string Feedback { get; set; }
    }
}
