//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEWAXP.Foundation.Integration.SmartCustAuthenticationSvc {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.portal.dewa.gov.ae/itd/")]
    public partial class Exception : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.portal.dewa.gov.ae/itd/")]
    public partial class GetLoginSessionCustomerAuthenticationResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.portal.dewa.gov.ae/itd/")]
    public partial class GetLoginSessionCustomerAuthentication : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string useridField;
        
        private string ipaddressField;
        
        private string issuervendoridField;
        
        private string issuersessionidField;
        
        private string providermerchantidField;
        
        private string providermerchantpasswordField;
        
        private string mobileosversionField;
        
        private string appversionField;
        
        private string appidentifierField;
        
        private string langField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string userid {
            get {
                return this.useridField;
            }
            set {
                this.useridField = value;
                this.RaisePropertyChanged("userid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ipaddress {
            get {
                return this.ipaddressField;
            }
            set {
                this.ipaddressField = value;
                this.RaisePropertyChanged("ipaddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string issuervendorid {
            get {
                return this.issuervendoridField;
            }
            set {
                this.issuervendoridField = value;
                this.RaisePropertyChanged("issuervendorid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string issuersessionid {
            get {
                return this.issuersessionidField;
            }
            set {
                this.issuersessionidField = value;
                this.RaisePropertyChanged("issuersessionid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string providermerchantid {
            get {
                return this.providermerchantidField;
            }
            set {
                this.providermerchantidField = value;
                this.RaisePropertyChanged("providermerchantid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string providermerchantpassword {
            get {
                return this.providermerchantpasswordField;
            }
            set {
                this.providermerchantpasswordField = value;
                this.RaisePropertyChanged("providermerchantpassword");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string mobileosversion {
            get {
                return this.mobileosversionField;
            }
            set {
                this.mobileosversionField = value;
                this.RaisePropertyChanged("mobileosversion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string appversion {
            get {
                return this.appversionField;
            }
            set {
                this.appversionField = value;
                this.RaisePropertyChanged("appversion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string appidentifier {
            get {
                return this.appidentifierField;
            }
            set {
                this.appidentifierField = value;
                this.RaisePropertyChanged("appidentifier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string lang {
            get {
                return this.langField;
            }
            set {
                this.langField = value;
                this.RaisePropertyChanged("lang");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.portal.dewa.gov.ae/itd/", ConfigurationName="SmartCustAuthenticationSvc.SmartCustAuthentication")]
    public interface SmartCustAuthentication {
        
        // CODEGEN: Generating message contract since the operation GetLoginSessionCustomerAuthentication is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(DEWAXP.Foundation.Integration.SmartCustAuthenticationSvc.Exception), Action="", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DEWAXP.Foundation.Integration.SmartCustAuthenticationSvc.GetLoginSessionCustomerAuthenticationResponse1 GetLoginSessionCustomerAuthentication(DEWAXP.Foundation.Integration.SmartCustAuthenticationSvc.GetLoginSessionCustomerAuthenticationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<DEWAXP.Foundation.Integration.SmartCustAuthenticationSvc.GetLoginSessionCustomerAuthenticationResponse1> GetLoginSessionCustomerAuthenticationAsync(DEWAXP.Foundation.Integration.SmartCustAuthenticationSvc.GetLoginSessionCustomerAuthenticationRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLoginSessionCustomerAuthenticationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.portal.dewa.gov.ae/itd/", Order=0)]
        public DEWAXP.Foundation.Integration.SmartCustAuthenticationSvc.GetLoginSessionCustomerAuthentication GetLoginSessionCustomerAuthentication;
        
        public GetLoginSessionCustomerAuthenticationRequest() {
        }
        
        public GetLoginSessionCustomerAuthenticationRequest(DEWAXP.Foundation.Integration.SmartCustAuthenticationSvc.GetLoginSessionCustomerAuthentication GetLoginSessionCustomerAuthentication) {
            this.GetLoginSessionCustomerAuthentication = GetLoginSessionCustomerAuthentication;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLoginSessionCustomerAuthenticationResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.portal.dewa.gov.ae/itd/", Order=0)]
        public DEWAXP.Foundation.Integration.SmartCustAuthenticationSvc.GetLoginSessionCustomerAuthenticationResponse GetLoginSessionCustomerAuthenticationResponse;
        
        public GetLoginSessionCustomerAuthenticationResponse1() {
        }
        
        public GetLoginSessionCustomerAuthenticationResponse1(DEWAXP.Foundation.Integration.SmartCustAuthenticationSvc.GetLoginSessionCustomerAuthenticationResponse GetLoginSessionCustomerAuthenticationResponse) {
            this.GetLoginSessionCustomerAuthenticationResponse = GetLoginSessionCustomerAuthenticationResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SmartCustAuthenticationChannel : DEWAXP.Foundation.Integration.SmartCustAuthenticationSvc.SmartCustAuthentication, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SmartCustAuthenticationClient : System.ServiceModel.ClientBase<DEWAXP.Foundation.Integration.SmartCustAuthenticationSvc.SmartCustAuthentication>, DEWAXP.Foundation.Integration.SmartCustAuthenticationSvc.SmartCustAuthentication {
        
        public SmartCustAuthenticationClient() {
        }
        
        public SmartCustAuthenticationClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SmartCustAuthenticationClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SmartCustAuthenticationClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SmartCustAuthenticationClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DEWAXP.Foundation.Integration.SmartCustAuthenticationSvc.GetLoginSessionCustomerAuthenticationResponse1 DEWAXP.Foundation.Integration.SmartCustAuthenticationSvc.SmartCustAuthentication.GetLoginSessionCustomerAuthentication(DEWAXP.Foundation.Integration.SmartCustAuthenticationSvc.GetLoginSessionCustomerAuthenticationRequest request) {
            return base.Channel.GetLoginSessionCustomerAuthentication(request);
        }
        
        public DEWAXP.Foundation.Integration.SmartCustAuthenticationSvc.GetLoginSessionCustomerAuthenticationResponse GetLoginSessionCustomerAuthentication(DEWAXP.Foundation.Integration.SmartCustAuthenticationSvc.GetLoginSessionCustomerAuthentication GetLoginSessionCustomerAuthentication1) {
            DEWAXP.Foundation.Integration.SmartCustAuthenticationSvc.GetLoginSessionCustomerAuthenticationRequest inValue = new DEWAXP.Foundation.Integration.SmartCustAuthenticationSvc.GetLoginSessionCustomerAuthenticationRequest();
            inValue.GetLoginSessionCustomerAuthentication = GetLoginSessionCustomerAuthentication1;
            DEWAXP.Foundation.Integration.SmartCustAuthenticationSvc.GetLoginSessionCustomerAuthenticationResponse1 retVal = ((DEWAXP.Foundation.Integration.SmartCustAuthenticationSvc.SmartCustAuthentication)(this)).GetLoginSessionCustomerAuthentication(inValue);
            return retVal.GetLoginSessionCustomerAuthenticationResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DEWAXP.Foundation.Integration.SmartCustAuthenticationSvc.GetLoginSessionCustomerAuthenticationResponse1> DEWAXP.Foundation.Integration.SmartCustAuthenticationSvc.SmartCustAuthentication.GetLoginSessionCustomerAuthenticationAsync(DEWAXP.Foundation.Integration.SmartCustAuthenticationSvc.GetLoginSessionCustomerAuthenticationRequest request) {
            return base.Channel.GetLoginSessionCustomerAuthenticationAsync(request);
        }
        
        public System.Threading.Tasks.Task<DEWAXP.Foundation.Integration.SmartCustAuthenticationSvc.GetLoginSessionCustomerAuthenticationResponse1> GetLoginSessionCustomerAuthenticationAsync(DEWAXP.Foundation.Integration.SmartCustAuthenticationSvc.GetLoginSessionCustomerAuthentication GetLoginSessionCustomerAuthentication) {
            DEWAXP.Foundation.Integration.SmartCustAuthenticationSvc.GetLoginSessionCustomerAuthenticationRequest inValue = new DEWAXP.Foundation.Integration.SmartCustAuthenticationSvc.GetLoginSessionCustomerAuthenticationRequest();
            inValue.GetLoginSessionCustomerAuthentication = GetLoginSessionCustomerAuthentication;
            return ((DEWAXP.Foundation.Integration.SmartCustAuthenticationSvc.SmartCustAuthentication)(this)).GetLoginSessionCustomerAuthenticationAsync(inValue);
        }
    }
}
