//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace DEWAXP.Foundation.Integration.ProjectDocumentGenerationSvc {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tempuri.org/DMS/Service1", ConfigurationName="ProjectDocumentGenerationSvc.DMS_LiveSoap")]
    public interface DMS_LiveSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DMS/Service1/DissconnectDocumentum", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string DissconnectDocumentum(string DMS_SessionID, string DMS_User_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DMS/Service1/DissconnectDocumentum", ReplyAction="*")]
        System.Threading.Tasks.Task<string> DissconnectDocumentumAsync(string DMS_SessionID, string DMS_User_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DMS/Service1/Update_Attribute", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Update_Attribute(string DMS_SessionID, string DMS_User_ID, string object_id, string attr_name, string attr_new_value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DMS/Service1/Update_Attribute", ReplyAction="*")]
        System.Threading.Tasks.Task<string> Update_AttributeAsync(string DMS_SessionID, string DMS_User_ID, string object_id, string attr_name, string attr_new_value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DMS/Service1/SearchInDoc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SearchInDoc(string DMS_SessionID, string DMS_User_ID, string DQL_Table_Name, string DQL_Where, string DQL_Select);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DMS/Service1/SearchInDoc", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SearchInDocAsync(string DMS_SessionID, string DMS_User_ID, string DQL_Table_Name, string DQL_Where, string DQL_Select);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DMS/Service1/GetFileFromDMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DEWAXP.Foundation.Integration.ProjectDocumentGenerationSvc.DMS_Properties GetFileFromDMS(string DMS_SessionID, string DMS_User_ID, string ObjectID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DMS/Service1/GetFileFromDMS", ReplyAction="*")]
        System.Threading.Tasks.Task<DEWAXP.Foundation.Integration.ProjectDocumentGenerationSvc.DMS_Properties> GetFileFromDMSAsync(string DMS_SessionID, string DMS_User_ID, string ObjectID);
        
        // CODEGEN: Parameter 'GetFileByeArrayFromDMSResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DMS/Service1/GetFileByeArrayFromDMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DEWAXP.Foundation.Integration.ProjectDocumentGenerationSvc.GetFileByeArrayFromDMSResponse GetFileByeArrayFromDMS(DEWAXP.Foundation.Integration.ProjectDocumentGenerationSvc.GetFileByeArrayFromDMSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DMS/Service1/GetFileByeArrayFromDMS", ReplyAction="*")]
        System.Threading.Tasks.Task<DEWAXP.Foundation.Integration.ProjectDocumentGenerationSvc.GetFileByeArrayFromDMSResponse> GetFileByeArrayFromDMSAsync(DEWAXP.Foundation.Integration.ProjectDocumentGenerationSvc.GetFileByeArrayFromDMSRequest request);
        
        // CODEGEN: Parameter 'FileBytesArray' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DMS/Service1/UploadFileToDMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DEWAXP.Foundation.Integration.ProjectDocumentGenerationSvc.UploadFileToDMSResponse UploadFileToDMS(DEWAXP.Foundation.Integration.ProjectDocumentGenerationSvc.UploadFileToDMSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DMS/Service1/UploadFileToDMS", ReplyAction="*")]
        System.Threading.Tasks.Task<DEWAXP.Foundation.Integration.ProjectDocumentGenerationSvc.UploadFileToDMSResponse> UploadFileToDMSAsync(DEWAXP.Foundation.Integration.ProjectDocumentGenerationSvc.UploadFileToDMSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DMS/Service1/ConvertToVirtual_Document", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ConvertToVirtual_Document(string DMS_SessionID, string DMS_User_ID, string ObjectID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DMS/Service1/ConvertToVirtual_Document", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ConvertToVirtual_DocumentAsync(string DMS_SessionID, string DMS_User_ID, string ObjectID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DMS/Service1/Move_File", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Move_File(string DMS_SessionID, string DMS_User_ID, string ObjectID, string New_Folder_Path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DMS/Service1/Move_File", ReplyAction="*")]
        System.Threading.Tasks.Task<string> Move_FileAsync(string DMS_SessionID, string DMS_User_ID, string ObjectID, string New_Folder_Path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DMS/Service1/isVirtual_Document", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string isVirtual_Document(string DMS_SessionID, string DMS_User_ID, string ObjectID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DMS/Service1/isVirtual_Document", ReplyAction="*")]
        System.Threading.Tasks.Task<string> isVirtual_DocumentAsync(string DMS_SessionID, string DMS_User_ID, string ObjectID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DMS/Service1/GetVirtual_Document_Childern", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetVirtual_Document_Childern(string DMS_SessionID, string DMS_User_ID, string VirtualDocumentObjectID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DMS/Service1/GetVirtual_Document_Childern", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetVirtual_Document_ChildernAsync(string DMS_SessionID, string DMS_User_ID, string VirtualDocumentObjectID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DMS/Service1/AddToVirtual_Document", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string AddToVirtual_Document(string DMS_SessionID, string DMS_User_ID, string r_object_id, string Virtual_Document_ObjectId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DMS/Service1/AddToVirtual_Document", ReplyAction="*")]
        System.Threading.Tasks.Task<string> AddToVirtual_DocumentAsync(string DMS_SessionID, string DMS_User_ID, string r_object_id, string Virtual_Document_ObjectId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DMS/Service1/Create_Folder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Create_Folder(string DMS_SessionID, string DMS_User_ID, string NewFolderPath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DMS/Service1/Create_Folder", ReplyAction="*")]
        System.Threading.Tasks.Task<string> Create_FolderAsync(string DMS_SessionID, string DMS_User_ID, string NewFolderPath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DMS/Service1/GetWebserviceVersion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetWebserviceVersion();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DMS/Service1/GetWebserviceVersion", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetWebserviceVersionAsync();
        
        // CODEGEN: Parameter 'FileBytesArray' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DMS/Service1/UploadFileToDMS_V1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DEWAXP.Foundation.Integration.ProjectDocumentGenerationSvc.UploadFileToDMS_V1Response UploadFileToDMS_V1(DEWAXP.Foundation.Integration.ProjectDocumentGenerationSvc.UploadFileToDMS_V1Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DMS/Service1/UploadFileToDMS_V1", ReplyAction="*")]
        System.Threading.Tasks.Task<DEWAXP.Foundation.Integration.ProjectDocumentGenerationSvc.UploadFileToDMS_V1Response> UploadFileToDMS_V1Async(DEWAXP.Foundation.Integration.ProjectDocumentGenerationSvc.UploadFileToDMS_V1Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DMS/Service1/ConnectToDocbase", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ConnectToDocbase(string User_ID, string Password, string strDocbase);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DMS/Service1/ConnectToDocbase", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ConnectToDocbaseAsync(string User_ID, string Password, string strDocbase);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DMS/Service1/Test_Docbase", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Test_Docbase(string strDocbase);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DMS/Service1/Test_Docbase", ReplyAction="*")]
        System.Threading.Tasks.Task<string> Test_DocbaseAsync(string strDocbase);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DMS/Service1/Change_Type", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Change_Type(string DMS_SessionID, string DMS_User_ID, string object_id, string current_type, string new_type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DMS/Service1/Change_Type", ReplyAction="*")]
        System.Threading.Tasks.Task<string> Change_TypeAsync(string DMS_SessionID, string DMS_User_ID, string object_id, string current_type, string new_type);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/DMS/Service1")]
    public partial class DMS_Properties : object, System.ComponentModel.INotifyPropertyChanged {
        
        private byte[] file_BytesField;
        
        private string file_NameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=0)]
        public byte[] File_Bytes {
            get {
                return this.file_BytesField;
            }
            set {
                this.file_BytesField = value;
                this.RaisePropertyChanged("File_Bytes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string File_Name {
            get {
                return this.file_NameField;
            }
            set {
                this.file_NameField = value;
                this.RaisePropertyChanged("File_Name");
            }
        }
        
        [field: NonSerialized]public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetFileByeArrayFromDMS", WrapperNamespace="http://tempuri.org/DMS/Service1", IsWrapped=true)]
    public partial class GetFileByeArrayFromDMSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/DMS/Service1", Order=0)]
        public string DMS_SessionID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/DMS/Service1", Order=1)]
        public string DMS_User_ID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/DMS/Service1", Order=2)]
        public string ObjectID;
        
        public GetFileByeArrayFromDMSRequest() {
        }
        
        public GetFileByeArrayFromDMSRequest(string DMS_SessionID, string DMS_User_ID, string ObjectID) {
            this.DMS_SessionID = DMS_SessionID;
            this.DMS_User_ID = DMS_User_ID;
            this.ObjectID = ObjectID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetFileByeArrayFromDMSResponse", WrapperNamespace="http://tempuri.org/DMS/Service1", IsWrapped=true)]
    public partial class GetFileByeArrayFromDMSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/DMS/Service1", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] GetFileByeArrayFromDMSResult;
        
        public GetFileByeArrayFromDMSResponse() {
        }
        
        public GetFileByeArrayFromDMSResponse(byte[] GetFileByeArrayFromDMSResult) {
            this.GetFileByeArrayFromDMSResult = GetFileByeArrayFromDMSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UploadFileToDMS", WrapperNamespace="http://tempuri.org/DMS/Service1", IsWrapped=true)]
    public partial class UploadFileToDMSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/DMS/Service1", Order=0)]
        public string DMS_SessionID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/DMS/Service1", Order=1)]
        public string DMS_User_ID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/DMS/Service1", Order=2)]
        public string DMS_Attributes;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/DMS/Service1", Order=3)]
        public string Documentum_Folder;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/DMS/Service1", Order=4)]
        public string Document_Type;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/DMS/Service1", Order=5)]
        public string FileType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/DMS/Service1", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] FileBytesArray;
        
        public UploadFileToDMSRequest() {
        }
        
        public UploadFileToDMSRequest(string DMS_SessionID, string DMS_User_ID, string DMS_Attributes, string Documentum_Folder, string Document_Type, string FileType, byte[] FileBytesArray) {
            this.DMS_SessionID = DMS_SessionID;
            this.DMS_User_ID = DMS_User_ID;
            this.DMS_Attributes = DMS_Attributes;
            this.Documentum_Folder = Documentum_Folder;
            this.Document_Type = Document_Type;
            this.FileType = FileType;
            this.FileBytesArray = FileBytesArray;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UploadFileToDMSResponse", WrapperNamespace="http://tempuri.org/DMS/Service1", IsWrapped=true)]
    public partial class UploadFileToDMSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/DMS/Service1", Order=0)]
        public string UploadFileToDMSResult;
        
        public UploadFileToDMSResponse() {
        }
        
        public UploadFileToDMSResponse(string UploadFileToDMSResult) {
            this.UploadFileToDMSResult = UploadFileToDMSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UploadFileToDMS_V1", WrapperNamespace="http://tempuri.org/DMS/Service1", IsWrapped=true)]
    public partial class UploadFileToDMS_V1Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/DMS/Service1", Order=0)]
        public string DMS_SessionID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/DMS/Service1", Order=1)]
        public string DMS_User_ID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/DMS/Service1", Order=2)]
        public string DMS_Attributes;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/DMS/Service1", Order=3)]
        public string Documentum_Folder;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/DMS/Service1", Order=4)]
        public string Document_Type;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/DMS/Service1", Order=5)]
        public string FileType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/DMS/Service1", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] FileBytesArray;
        
        public UploadFileToDMS_V1Request() {
        }
        
        public UploadFileToDMS_V1Request(string DMS_SessionID, string DMS_User_ID, string DMS_Attributes, string Documentum_Folder, string Document_Type, string FileType, byte[] FileBytesArray) {
            this.DMS_SessionID = DMS_SessionID;
            this.DMS_User_ID = DMS_User_ID;
            this.DMS_Attributes = DMS_Attributes;
            this.Documentum_Folder = Documentum_Folder;
            this.Document_Type = Document_Type;
            this.FileType = FileType;
            this.FileBytesArray = FileBytesArray;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UploadFileToDMS_V1Response", WrapperNamespace="http://tempuri.org/DMS/Service1", IsWrapped=true)]
    public partial class UploadFileToDMS_V1Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/DMS/Service1", Order=0)]
        public string UploadFileToDMS_V1Result;
        
        public UploadFileToDMS_V1Response() {
        }
        
        public UploadFileToDMS_V1Response(string UploadFileToDMS_V1Result) {
            this.UploadFileToDMS_V1Result = UploadFileToDMS_V1Result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DMS_LiveSoapChannel : DEWAXP.Foundation.Integration.ProjectDocumentGenerationSvc.DMS_LiveSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DMS_LiveSoapClient : System.ServiceModel.ClientBase<DEWAXP.Foundation.Integration.ProjectDocumentGenerationSvc.DMS_LiveSoap>, DEWAXP.Foundation.Integration.ProjectDocumentGenerationSvc.DMS_LiveSoap {
        
        public DMS_LiveSoapClient() {
        }
        
        public DMS_LiveSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DMS_LiveSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DMS_LiveSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DMS_LiveSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string DissconnectDocumentum(string DMS_SessionID, string DMS_User_ID) {
            return base.Channel.DissconnectDocumentum(DMS_SessionID, DMS_User_ID);
        }
        
        public System.Threading.Tasks.Task<string> DissconnectDocumentumAsync(string DMS_SessionID, string DMS_User_ID) {
            return base.Channel.DissconnectDocumentumAsync(DMS_SessionID, DMS_User_ID);
        }
        
        public string Update_Attribute(string DMS_SessionID, string DMS_User_ID, string object_id, string attr_name, string attr_new_value) {
            return base.Channel.Update_Attribute(DMS_SessionID, DMS_User_ID, object_id, attr_name, attr_new_value);
        }
        
        public System.Threading.Tasks.Task<string> Update_AttributeAsync(string DMS_SessionID, string DMS_User_ID, string object_id, string attr_name, string attr_new_value) {
            return base.Channel.Update_AttributeAsync(DMS_SessionID, DMS_User_ID, object_id, attr_name, attr_new_value);
        }
        
        public string SearchInDoc(string DMS_SessionID, string DMS_User_ID, string DQL_Table_Name, string DQL_Where, string DQL_Select) {
            return base.Channel.SearchInDoc(DMS_SessionID, DMS_User_ID, DQL_Table_Name, DQL_Where, DQL_Select);
        }
        
        public System.Threading.Tasks.Task<string> SearchInDocAsync(string DMS_SessionID, string DMS_User_ID, string DQL_Table_Name, string DQL_Where, string DQL_Select) {
            return base.Channel.SearchInDocAsync(DMS_SessionID, DMS_User_ID, DQL_Table_Name, DQL_Where, DQL_Select);
        }
        
        public DEWAXP.Foundation.Integration.ProjectDocumentGenerationSvc.DMS_Properties GetFileFromDMS(string DMS_SessionID, string DMS_User_ID, string ObjectID) {
            return base.Channel.GetFileFromDMS(DMS_SessionID, DMS_User_ID, ObjectID);
        }
        
        public System.Threading.Tasks.Task<DEWAXP.Foundation.Integration.ProjectDocumentGenerationSvc.DMS_Properties> GetFileFromDMSAsync(string DMS_SessionID, string DMS_User_ID, string ObjectID) {
            return base.Channel.GetFileFromDMSAsync(DMS_SessionID, DMS_User_ID, ObjectID);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DEWAXP.Foundation.Integration.ProjectDocumentGenerationSvc.GetFileByeArrayFromDMSResponse DEWAXP.Foundation.Integration.ProjectDocumentGenerationSvc.DMS_LiveSoap.GetFileByeArrayFromDMS(DEWAXP.Foundation.Integration.ProjectDocumentGenerationSvc.GetFileByeArrayFromDMSRequest request) {
            return base.Channel.GetFileByeArrayFromDMS(request);
        }
        
        public byte[] GetFileByeArrayFromDMS(string DMS_SessionID, string DMS_User_ID, string ObjectID) {
            DEWAXP.Foundation.Integration.ProjectDocumentGenerationSvc.GetFileByeArrayFromDMSRequest inValue = new DEWAXP.Foundation.Integration.ProjectDocumentGenerationSvc.GetFileByeArrayFromDMSRequest();
            inValue.DMS_SessionID = DMS_SessionID;
            inValue.DMS_User_ID = DMS_User_ID;
            inValue.ObjectID = ObjectID;
            DEWAXP.Foundation.Integration.ProjectDocumentGenerationSvc.GetFileByeArrayFromDMSResponse retVal = ((DEWAXP.Foundation.Integration.ProjectDocumentGenerationSvc.DMS_LiveSoap)(this)).GetFileByeArrayFromDMS(inValue);
            return retVal.GetFileByeArrayFromDMSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DEWAXP.Foundation.Integration.ProjectDocumentGenerationSvc.GetFileByeArrayFromDMSResponse> DEWAXP.Foundation.Integration.ProjectDocumentGenerationSvc.DMS_LiveSoap.GetFileByeArrayFromDMSAsync(DEWAXP.Foundation.Integration.ProjectDocumentGenerationSvc.GetFileByeArrayFromDMSRequest request) {
            return base.Channel.GetFileByeArrayFromDMSAsync(request);
        }
        
        public System.Threading.Tasks.Task<DEWAXP.Foundation.Integration.ProjectDocumentGenerationSvc.GetFileByeArrayFromDMSResponse> GetFileByeArrayFromDMSAsync(string DMS_SessionID, string DMS_User_ID, string ObjectID) {
            DEWAXP.Foundation.Integration.ProjectDocumentGenerationSvc.GetFileByeArrayFromDMSRequest inValue = new DEWAXP.Foundation.Integration.ProjectDocumentGenerationSvc.GetFileByeArrayFromDMSRequest();
            inValue.DMS_SessionID = DMS_SessionID;
            inValue.DMS_User_ID = DMS_User_ID;
            inValue.ObjectID = ObjectID;
            return ((DEWAXP.Foundation.Integration.ProjectDocumentGenerationSvc.DMS_LiveSoap)(this)).GetFileByeArrayFromDMSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DEWAXP.Foundation.Integration.ProjectDocumentGenerationSvc.UploadFileToDMSResponse DEWAXP.Foundation.Integration.ProjectDocumentGenerationSvc.DMS_LiveSoap.UploadFileToDMS(DEWAXP.Foundation.Integration.ProjectDocumentGenerationSvc.UploadFileToDMSRequest request) {
            return base.Channel.UploadFileToDMS(request);
        }
        
        public string UploadFileToDMS(string DMS_SessionID, string DMS_User_ID, string DMS_Attributes, string Documentum_Folder, string Document_Type, string FileType, byte[] FileBytesArray) {
            DEWAXP.Foundation.Integration.ProjectDocumentGenerationSvc.UploadFileToDMSRequest inValue = new DEWAXP.Foundation.Integration.ProjectDocumentGenerationSvc.UploadFileToDMSRequest();
            inValue.DMS_SessionID = DMS_SessionID;
            inValue.DMS_User_ID = DMS_User_ID;
            inValue.DMS_Attributes = DMS_Attributes;
            inValue.Documentum_Folder = Documentum_Folder;
            inValue.Document_Type = Document_Type;
            inValue.FileType = FileType;
            inValue.FileBytesArray = FileBytesArray;
            DEWAXP.Foundation.Integration.ProjectDocumentGenerationSvc.UploadFileToDMSResponse retVal = ((DEWAXP.Foundation.Integration.ProjectDocumentGenerationSvc.DMS_LiveSoap)(this)).UploadFileToDMS(inValue);
            return retVal.UploadFileToDMSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DEWAXP.Foundation.Integration.ProjectDocumentGenerationSvc.UploadFileToDMSResponse> DEWAXP.Foundation.Integration.ProjectDocumentGenerationSvc.DMS_LiveSoap.UploadFileToDMSAsync(DEWAXP.Foundation.Integration.ProjectDocumentGenerationSvc.UploadFileToDMSRequest request) {
            return base.Channel.UploadFileToDMSAsync(request);
        }
        
        public System.Threading.Tasks.Task<DEWAXP.Foundation.Integration.ProjectDocumentGenerationSvc.UploadFileToDMSResponse> UploadFileToDMSAsync(string DMS_SessionID, string DMS_User_ID, string DMS_Attributes, string Documentum_Folder, string Document_Type, string FileType, byte[] FileBytesArray) {
            DEWAXP.Foundation.Integration.ProjectDocumentGenerationSvc.UploadFileToDMSRequest inValue = new DEWAXP.Foundation.Integration.ProjectDocumentGenerationSvc.UploadFileToDMSRequest();
            inValue.DMS_SessionID = DMS_SessionID;
            inValue.DMS_User_ID = DMS_User_ID;
            inValue.DMS_Attributes = DMS_Attributes;
            inValue.Documentum_Folder = Documentum_Folder;
            inValue.Document_Type = Document_Type;
            inValue.FileType = FileType;
            inValue.FileBytesArray = FileBytesArray;
            return ((DEWAXP.Foundation.Integration.ProjectDocumentGenerationSvc.DMS_LiveSoap)(this)).UploadFileToDMSAsync(inValue);
        }
        
        public string ConvertToVirtual_Document(string DMS_SessionID, string DMS_User_ID, string ObjectID) {
            return base.Channel.ConvertToVirtual_Document(DMS_SessionID, DMS_User_ID, ObjectID);
        }
        
        public System.Threading.Tasks.Task<string> ConvertToVirtual_DocumentAsync(string DMS_SessionID, string DMS_User_ID, string ObjectID) {
            return base.Channel.ConvertToVirtual_DocumentAsync(DMS_SessionID, DMS_User_ID, ObjectID);
        }
        
        public string Move_File(string DMS_SessionID, string DMS_User_ID, string ObjectID, string New_Folder_Path) {
            return base.Channel.Move_File(DMS_SessionID, DMS_User_ID, ObjectID, New_Folder_Path);
        }
        
        public System.Threading.Tasks.Task<string> Move_FileAsync(string DMS_SessionID, string DMS_User_ID, string ObjectID, string New_Folder_Path) {
            return base.Channel.Move_FileAsync(DMS_SessionID, DMS_User_ID, ObjectID, New_Folder_Path);
        }
        
        public string isVirtual_Document(string DMS_SessionID, string DMS_User_ID, string ObjectID) {
            return base.Channel.isVirtual_Document(DMS_SessionID, DMS_User_ID, ObjectID);
        }
        
        public System.Threading.Tasks.Task<string> isVirtual_DocumentAsync(string DMS_SessionID, string DMS_User_ID, string ObjectID) {
            return base.Channel.isVirtual_DocumentAsync(DMS_SessionID, DMS_User_ID, ObjectID);
        }
        
        public string GetVirtual_Document_Childern(string DMS_SessionID, string DMS_User_ID, string VirtualDocumentObjectID) {
            return base.Channel.GetVirtual_Document_Childern(DMS_SessionID, DMS_User_ID, VirtualDocumentObjectID);
        }
        
        public System.Threading.Tasks.Task<string> GetVirtual_Document_ChildernAsync(string DMS_SessionID, string DMS_User_ID, string VirtualDocumentObjectID) {
            return base.Channel.GetVirtual_Document_ChildernAsync(DMS_SessionID, DMS_User_ID, VirtualDocumentObjectID);
        }
        
        public string AddToVirtual_Document(string DMS_SessionID, string DMS_User_ID, string r_object_id, string Virtual_Document_ObjectId) {
            return base.Channel.AddToVirtual_Document(DMS_SessionID, DMS_User_ID, r_object_id, Virtual_Document_ObjectId);
        }
        
        public System.Threading.Tasks.Task<string> AddToVirtual_DocumentAsync(string DMS_SessionID, string DMS_User_ID, string r_object_id, string Virtual_Document_ObjectId) {
            return base.Channel.AddToVirtual_DocumentAsync(DMS_SessionID, DMS_User_ID, r_object_id, Virtual_Document_ObjectId);
        }
        
        public string Create_Folder(string DMS_SessionID, string DMS_User_ID, string NewFolderPath) {
            return base.Channel.Create_Folder(DMS_SessionID, DMS_User_ID, NewFolderPath);
        }
        
        public System.Threading.Tasks.Task<string> Create_FolderAsync(string DMS_SessionID, string DMS_User_ID, string NewFolderPath) {
            return base.Channel.Create_FolderAsync(DMS_SessionID, DMS_User_ID, NewFolderPath);
        }
        
        public string GetWebserviceVersion() {
            return base.Channel.GetWebserviceVersion();
        }
        
        public System.Threading.Tasks.Task<string> GetWebserviceVersionAsync() {
            return base.Channel.GetWebserviceVersionAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DEWAXP.Foundation.Integration.ProjectDocumentGenerationSvc.UploadFileToDMS_V1Response DEWAXP.Foundation.Integration.ProjectDocumentGenerationSvc.DMS_LiveSoap.UploadFileToDMS_V1(DEWAXP.Foundation.Integration.ProjectDocumentGenerationSvc.UploadFileToDMS_V1Request request) {
            return base.Channel.UploadFileToDMS_V1(request);
        }
        
        public string UploadFileToDMS_V1(string DMS_SessionID, string DMS_User_ID, string DMS_Attributes, string Documentum_Folder, string Document_Type, string FileType, byte[] FileBytesArray) {
            DEWAXP.Foundation.Integration.ProjectDocumentGenerationSvc.UploadFileToDMS_V1Request inValue = new DEWAXP.Foundation.Integration.ProjectDocumentGenerationSvc.UploadFileToDMS_V1Request();
            inValue.DMS_SessionID = DMS_SessionID;
            inValue.DMS_User_ID = DMS_User_ID;
            inValue.DMS_Attributes = DMS_Attributes;
            inValue.Documentum_Folder = Documentum_Folder;
            inValue.Document_Type = Document_Type;
            inValue.FileType = FileType;
            inValue.FileBytesArray = FileBytesArray;
            DEWAXP.Foundation.Integration.ProjectDocumentGenerationSvc.UploadFileToDMS_V1Response retVal = ((DEWAXP.Foundation.Integration.ProjectDocumentGenerationSvc.DMS_LiveSoap)(this)).UploadFileToDMS_V1(inValue);
            return retVal.UploadFileToDMS_V1Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DEWAXP.Foundation.Integration.ProjectDocumentGenerationSvc.UploadFileToDMS_V1Response> DEWAXP.Foundation.Integration.ProjectDocumentGenerationSvc.DMS_LiveSoap.UploadFileToDMS_V1Async(DEWAXP.Foundation.Integration.ProjectDocumentGenerationSvc.UploadFileToDMS_V1Request request) {
            return base.Channel.UploadFileToDMS_V1Async(request);
        }
        
        public System.Threading.Tasks.Task<DEWAXP.Foundation.Integration.ProjectDocumentGenerationSvc.UploadFileToDMS_V1Response> UploadFileToDMS_V1Async(string DMS_SessionID, string DMS_User_ID, string DMS_Attributes, string Documentum_Folder, string Document_Type, string FileType, byte[] FileBytesArray) {
            DEWAXP.Foundation.Integration.ProjectDocumentGenerationSvc.UploadFileToDMS_V1Request inValue = new DEWAXP.Foundation.Integration.ProjectDocumentGenerationSvc.UploadFileToDMS_V1Request();
            inValue.DMS_SessionID = DMS_SessionID;
            inValue.DMS_User_ID = DMS_User_ID;
            inValue.DMS_Attributes = DMS_Attributes;
            inValue.Documentum_Folder = Documentum_Folder;
            inValue.Document_Type = Document_Type;
            inValue.FileType = FileType;
            inValue.FileBytesArray = FileBytesArray;
            return ((DEWAXP.Foundation.Integration.ProjectDocumentGenerationSvc.DMS_LiveSoap)(this)).UploadFileToDMS_V1Async(inValue);
        }
        
        public string ConnectToDocbase(string User_ID, string Password, string strDocbase) {
            return base.Channel.ConnectToDocbase(User_ID, Password, strDocbase);
        }
        
        public System.Threading.Tasks.Task<string> ConnectToDocbaseAsync(string User_ID, string Password, string strDocbase) {
            return base.Channel.ConnectToDocbaseAsync(User_ID, Password, strDocbase);
        }
        
        public string Test_Docbase(string strDocbase) {
            return base.Channel.Test_Docbase(strDocbase);
        }
        
        public System.Threading.Tasks.Task<string> Test_DocbaseAsync(string strDocbase) {
            return base.Channel.Test_DocbaseAsync(strDocbase);
        }
        
        public string Change_Type(string DMS_SessionID, string DMS_User_ID, string object_id, string current_type, string new_type) {
            return base.Channel.Change_Type(DMS_SessionID, DMS_User_ID, object_id, current_type, new_type);
        }
        
        public System.Threading.Tasks.Task<string> Change_TypeAsync(string DMS_SessionID, string DMS_User_ID, string object_id, string current_type, string new_type) {
            return base.Channel.Change_TypeAsync(DMS_SessionID, DMS_User_ID, object_id, current_type, new_type);
        }
    }
}
