//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEWAXP.Foundation.Integration.QmsStatusSvc {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservice.gms.com.my", ConfigurationName="QmsStatusSvc.QmsStatus")]
    public interface QmsStatus {
        
        // CODEGEN: Generating message contract since element name wsGetServiceStatusListReq from namespace http://webservice.gms.com.my is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        DEWAXP.Foundation.Integration.QmsStatusSvc.wsGetServiceStatusListResponse wsGetServiceStatusList(DEWAXP.Foundation.Integration.QmsStatusSvc.wsGetServiceStatusListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<DEWAXP.Foundation.Integration.QmsStatusSvc.wsGetServiceStatusListResponse> wsGetServiceStatusListAsync(DEWAXP.Foundation.Integration.QmsStatusSvc.wsGetServiceStatusListRequest request);
        
        // CODEGEN: Generating message contract since element name wsGetBranchServiceStatusReq from namespace http://webservice.gms.com.my is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        DEWAXP.Foundation.Integration.QmsStatusSvc.wsGetBranchServiceStatusResponse wsGetBranchServiceStatus(DEWAXP.Foundation.Integration.QmsStatusSvc.wsGetBranchServiceStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<DEWAXP.Foundation.Integration.QmsStatusSvc.wsGetBranchServiceStatusResponse> wsGetBranchServiceStatusAsync(DEWAXP.Foundation.Integration.QmsStatusSvc.wsGetBranchServiceStatusRequest request);
        
        // CODEGEN: Generating message contract since element name wsGetServingTicketReq from namespace http://webservice.gms.com.my is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        DEWAXP.Foundation.Integration.QmsStatusSvc.wsGetServingTicketResponse wsGetServingTicket(DEWAXP.Foundation.Integration.QmsStatusSvc.wsGetServingTicketRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<DEWAXP.Foundation.Integration.QmsStatusSvc.wsGetServingTicketResponse> wsGetServingTicketAsync(DEWAXP.Foundation.Integration.QmsStatusSvc.wsGetServingTicketRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class wsGetServiceStatusListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="wsGetServiceStatusList", Namespace="http://webservice.gms.com.my", Order=0)]
        public DEWAXP.Foundation.Integration.QmsStatusSvc.wsGetServiceStatusListRequestBody Body;
        
        public wsGetServiceStatusListRequest() {
        }
        
        public wsGetServiceStatusListRequest(DEWAXP.Foundation.Integration.QmsStatusSvc.wsGetServiceStatusListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservice.gms.com.my")]
    public partial class wsGetServiceStatusListRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string wsGetServiceStatusListReq;
        
        public wsGetServiceStatusListRequestBody() {
        }
        
        public wsGetServiceStatusListRequestBody(string wsGetServiceStatusListReq) {
            this.wsGetServiceStatusListReq = wsGetServiceStatusListReq;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class wsGetServiceStatusListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="wsGetServiceStatusListResponse", Namespace="http://webservice.gms.com.my", Order=0)]
        public DEWAXP.Foundation.Integration.QmsStatusSvc.wsGetServiceStatusListResponseBody Body;
        
        public wsGetServiceStatusListResponse() {
        }
        
        public wsGetServiceStatusListResponse(DEWAXP.Foundation.Integration.QmsStatusSvc.wsGetServiceStatusListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservice.gms.com.my")]
    public partial class wsGetServiceStatusListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string wsGetServiceStatusListReturn;
        
        public wsGetServiceStatusListResponseBody() {
        }
        
        public wsGetServiceStatusListResponseBody(string wsGetServiceStatusListReturn) {
            this.wsGetServiceStatusListReturn = wsGetServiceStatusListReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class wsGetBranchServiceStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="wsGetBranchServiceStatus", Namespace="http://webservice.gms.com.my", Order=0)]
        public DEWAXP.Foundation.Integration.QmsStatusSvc.wsGetBranchServiceStatusRequestBody Body;
        
        public wsGetBranchServiceStatusRequest() {
        }
        
        public wsGetBranchServiceStatusRequest(DEWAXP.Foundation.Integration.QmsStatusSvc.wsGetBranchServiceStatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservice.gms.com.my")]
    public partial class wsGetBranchServiceStatusRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string wsGetBranchServiceStatusReq;
        
        public wsGetBranchServiceStatusRequestBody() {
        }
        
        public wsGetBranchServiceStatusRequestBody(string wsGetBranchServiceStatusReq) {
            this.wsGetBranchServiceStatusReq = wsGetBranchServiceStatusReq;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class wsGetBranchServiceStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="wsGetBranchServiceStatusResponse", Namespace="http://webservice.gms.com.my", Order=0)]
        public DEWAXP.Foundation.Integration.QmsStatusSvc.wsGetBranchServiceStatusResponseBody Body;
        
        public wsGetBranchServiceStatusResponse() {
        }
        
        public wsGetBranchServiceStatusResponse(DEWAXP.Foundation.Integration.QmsStatusSvc.wsGetBranchServiceStatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservice.gms.com.my")]
    public partial class wsGetBranchServiceStatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string wsGetBranchServiceStatusReturn;
        
        public wsGetBranchServiceStatusResponseBody() {
        }
        
        public wsGetBranchServiceStatusResponseBody(string wsGetBranchServiceStatusReturn) {
            this.wsGetBranchServiceStatusReturn = wsGetBranchServiceStatusReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class wsGetServingTicketRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="wsGetServingTicket", Namespace="http://webservice.gms.com.my", Order=0)]
        public DEWAXP.Foundation.Integration.QmsStatusSvc.wsGetServingTicketRequestBody Body;
        
        public wsGetServingTicketRequest() {
        }
        
        public wsGetServingTicketRequest(DEWAXP.Foundation.Integration.QmsStatusSvc.wsGetServingTicketRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservice.gms.com.my")]
    public partial class wsGetServingTicketRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string wsGetServingTicketReq;
        
        public wsGetServingTicketRequestBody() {
        }
        
        public wsGetServingTicketRequestBody(string wsGetServingTicketReq) {
            this.wsGetServingTicketReq = wsGetServingTicketReq;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class wsGetServingTicketResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="wsGetServingTicketResponse", Namespace="http://webservice.gms.com.my", Order=0)]
        public DEWAXP.Foundation.Integration.QmsStatusSvc.wsGetServingTicketResponseBody Body;
        
        public wsGetServingTicketResponse() {
        }
        
        public wsGetServingTicketResponse(DEWAXP.Foundation.Integration.QmsStatusSvc.wsGetServingTicketResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservice.gms.com.my")]
    public partial class wsGetServingTicketResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string wsGetServingTicketReturn;
        
        public wsGetServingTicketResponseBody() {
        }
        
        public wsGetServingTicketResponseBody(string wsGetServingTicketReturn) {
            this.wsGetServingTicketReturn = wsGetServingTicketReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface QmsStatusChannel : DEWAXP.Foundation.Integration.QmsStatusSvc.QmsStatus, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QmsStatusClient : System.ServiceModel.ClientBase<DEWAXP.Foundation.Integration.QmsStatusSvc.QmsStatus>, DEWAXP.Foundation.Integration.QmsStatusSvc.QmsStatus {
        
        public QmsStatusClient() {
        }
        
        public QmsStatusClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public QmsStatusClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QmsStatusClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QmsStatusClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DEWAXP.Foundation.Integration.QmsStatusSvc.wsGetServiceStatusListResponse DEWAXP.Foundation.Integration.QmsStatusSvc.QmsStatus.wsGetServiceStatusList(DEWAXP.Foundation.Integration.QmsStatusSvc.wsGetServiceStatusListRequest request) {
            return base.Channel.wsGetServiceStatusList(request);
        }
        
        public string wsGetServiceStatusList(string wsGetServiceStatusListReq) {
            DEWAXP.Foundation.Integration.QmsStatusSvc.wsGetServiceStatusListRequest inValue = new DEWAXP.Foundation.Integration.QmsStatusSvc.wsGetServiceStatusListRequest();
            inValue.Body = new DEWAXP.Foundation.Integration.QmsStatusSvc.wsGetServiceStatusListRequestBody();
            inValue.Body.wsGetServiceStatusListReq = wsGetServiceStatusListReq;
            DEWAXP.Foundation.Integration.QmsStatusSvc.wsGetServiceStatusListResponse retVal = ((DEWAXP.Foundation.Integration.QmsStatusSvc.QmsStatus)(this)).wsGetServiceStatusList(inValue);
            return retVal.Body.wsGetServiceStatusListReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DEWAXP.Foundation.Integration.QmsStatusSvc.wsGetServiceStatusListResponse> DEWAXP.Foundation.Integration.QmsStatusSvc.QmsStatus.wsGetServiceStatusListAsync(DEWAXP.Foundation.Integration.QmsStatusSvc.wsGetServiceStatusListRequest request) {
            return base.Channel.wsGetServiceStatusListAsync(request);
        }
        
        public System.Threading.Tasks.Task<DEWAXP.Foundation.Integration.QmsStatusSvc.wsGetServiceStatusListResponse> wsGetServiceStatusListAsync(string wsGetServiceStatusListReq) {
            DEWAXP.Foundation.Integration.QmsStatusSvc.wsGetServiceStatusListRequest inValue = new DEWAXP.Foundation.Integration.QmsStatusSvc.wsGetServiceStatusListRequest();
            inValue.Body = new DEWAXP.Foundation.Integration.QmsStatusSvc.wsGetServiceStatusListRequestBody();
            inValue.Body.wsGetServiceStatusListReq = wsGetServiceStatusListReq;
            return ((DEWAXP.Foundation.Integration.QmsStatusSvc.QmsStatus)(this)).wsGetServiceStatusListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DEWAXP.Foundation.Integration.QmsStatusSvc.wsGetBranchServiceStatusResponse DEWAXP.Foundation.Integration.QmsStatusSvc.QmsStatus.wsGetBranchServiceStatus(DEWAXP.Foundation.Integration.QmsStatusSvc.wsGetBranchServiceStatusRequest request) {
            return base.Channel.wsGetBranchServiceStatus(request);
        }
        
        public string wsGetBranchServiceStatus(string wsGetBranchServiceStatusReq) {
            DEWAXP.Foundation.Integration.QmsStatusSvc.wsGetBranchServiceStatusRequest inValue = new DEWAXP.Foundation.Integration.QmsStatusSvc.wsGetBranchServiceStatusRequest();
            inValue.Body = new DEWAXP.Foundation.Integration.QmsStatusSvc.wsGetBranchServiceStatusRequestBody();
            inValue.Body.wsGetBranchServiceStatusReq = wsGetBranchServiceStatusReq;
            DEWAXP.Foundation.Integration.QmsStatusSvc.wsGetBranchServiceStatusResponse retVal = ((DEWAXP.Foundation.Integration.QmsStatusSvc.QmsStatus)(this)).wsGetBranchServiceStatus(inValue);
            return retVal.Body.wsGetBranchServiceStatusReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DEWAXP.Foundation.Integration.QmsStatusSvc.wsGetBranchServiceStatusResponse> DEWAXP.Foundation.Integration.QmsStatusSvc.QmsStatus.wsGetBranchServiceStatusAsync(DEWAXP.Foundation.Integration.QmsStatusSvc.wsGetBranchServiceStatusRequest request) {
            return base.Channel.wsGetBranchServiceStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<DEWAXP.Foundation.Integration.QmsStatusSvc.wsGetBranchServiceStatusResponse> wsGetBranchServiceStatusAsync(string wsGetBranchServiceStatusReq) {
            DEWAXP.Foundation.Integration.QmsStatusSvc.wsGetBranchServiceStatusRequest inValue = new DEWAXP.Foundation.Integration.QmsStatusSvc.wsGetBranchServiceStatusRequest();
            inValue.Body = new DEWAXP.Foundation.Integration.QmsStatusSvc.wsGetBranchServiceStatusRequestBody();
            inValue.Body.wsGetBranchServiceStatusReq = wsGetBranchServiceStatusReq;
            return ((DEWAXP.Foundation.Integration.QmsStatusSvc.QmsStatus)(this)).wsGetBranchServiceStatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DEWAXP.Foundation.Integration.QmsStatusSvc.wsGetServingTicketResponse DEWAXP.Foundation.Integration.QmsStatusSvc.QmsStatus.wsGetServingTicket(DEWAXP.Foundation.Integration.QmsStatusSvc.wsGetServingTicketRequest request) {
            return base.Channel.wsGetServingTicket(request);
        }
        
        public string wsGetServingTicket(string wsGetServingTicketReq) {
            DEWAXP.Foundation.Integration.QmsStatusSvc.wsGetServingTicketRequest inValue = new DEWAXP.Foundation.Integration.QmsStatusSvc.wsGetServingTicketRequest();
            inValue.Body = new DEWAXP.Foundation.Integration.QmsStatusSvc.wsGetServingTicketRequestBody();
            inValue.Body.wsGetServingTicketReq = wsGetServingTicketReq;
            DEWAXP.Foundation.Integration.QmsStatusSvc.wsGetServingTicketResponse retVal = ((DEWAXP.Foundation.Integration.QmsStatusSvc.QmsStatus)(this)).wsGetServingTicket(inValue);
            return retVal.Body.wsGetServingTicketReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DEWAXP.Foundation.Integration.QmsStatusSvc.wsGetServingTicketResponse> DEWAXP.Foundation.Integration.QmsStatusSvc.QmsStatus.wsGetServingTicketAsync(DEWAXP.Foundation.Integration.QmsStatusSvc.wsGetServingTicketRequest request) {
            return base.Channel.wsGetServingTicketAsync(request);
        }
        
        public System.Threading.Tasks.Task<DEWAXP.Foundation.Integration.QmsStatusSvc.wsGetServingTicketResponse> wsGetServingTicketAsync(string wsGetServingTicketReq) {
            DEWAXP.Foundation.Integration.QmsStatusSvc.wsGetServingTicketRequest inValue = new DEWAXP.Foundation.Integration.QmsStatusSvc.wsGetServingTicketRequest();
            inValue.Body = new DEWAXP.Foundation.Integration.QmsStatusSvc.wsGetServingTicketRequestBody();
            inValue.Body.wsGetServingTicketReq = wsGetServingTicketReq;
            return ((DEWAXP.Foundation.Integration.QmsStatusSvc.QmsStatus)(this)).wsGetServingTicketAsync(inValue);
        }
    }
}
