//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEWAXP.Foundation.Integration.EFormSvc {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EFormSvc.eFormSoap")]
    public interface eFormSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Query_Ework_DB", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Query_Ework_DB(string sql, string DB_Username, string DB_Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Query_Ework_DB", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Query_Ework_DBAsync(string sql, string DB_Username, string DB_Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SubmitNewForm", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SubmitNewForm(string Xml_FormValues, string MapName, string MapAction);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SubmitNewForm", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SubmitNewFormAsync(string Xml_FormValues, string MapName, string MapAction);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateForm", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string UpdateForm(string eFolderId, string Xml_FormValues, string MapName, string MapAction);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateForm", ReplyAction="*")]
        System.Threading.Tasks.Task<string> UpdateFormAsync(string eFolderId, string Xml_FormValues, string MapName, string MapAction);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface eFormSoapChannel : DEWAXP.Foundation.Integration.EFormSvc.eFormSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class eFormSoapClient : System.ServiceModel.ClientBase<DEWAXP.Foundation.Integration.EFormSvc.eFormSoap>, DEWAXP.Foundation.Integration.EFormSvc.eFormSoap {
        
        public eFormSoapClient() {
        }
        
        public eFormSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public eFormSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public eFormSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public eFormSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet Query_Ework_DB(string sql, string DB_Username, string DB_Password) {
            return base.Channel.Query_Ework_DB(sql, DB_Username, DB_Password);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Query_Ework_DBAsync(string sql, string DB_Username, string DB_Password) {
            return base.Channel.Query_Ework_DBAsync(sql, DB_Username, DB_Password);
        }
        
        public string SubmitNewForm(string Xml_FormValues, string MapName, string MapAction) {
            return base.Channel.SubmitNewForm(Xml_FormValues, MapName, MapAction);
        }
        
        public System.Threading.Tasks.Task<string> SubmitNewFormAsync(string Xml_FormValues, string MapName, string MapAction) {
            return base.Channel.SubmitNewFormAsync(Xml_FormValues, MapName, MapAction);
        }
        
        public string UpdateForm(string eFolderId, string Xml_FormValues, string MapName, string MapAction) {
            return base.Channel.UpdateForm(eFolderId, Xml_FormValues, MapName, MapAction);
        }
        
        public System.Threading.Tasks.Task<string> UpdateFormAsync(string eFolderId, string Xml_FormValues, string MapName, string MapAction) {
            return base.Channel.UpdateFormAsync(eFolderId, Xml_FormValues, MapName, MapAction);
        }
    }
}
