//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEWAXP.Foundation.Integration.QmsConfigSvc {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservice.gms.com.my", ConfigurationName="QmsConfigSvc.QmsConfig")]
    public interface QmsConfig {
        
        // CODEGEN: Generating message contract since element name wsGetBranchListReq from namespace http://webservice.gms.com.my is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        DEWAXP.Foundation.Integration.QmsConfigSvc.wsGetBranchListResponse wsGetBranchList(DEWAXP.Foundation.Integration.QmsConfigSvc.wsGetBranchListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<DEWAXP.Foundation.Integration.QmsConfigSvc.wsGetBranchListResponse> wsGetBranchListAsync(DEWAXP.Foundation.Integration.QmsConfigSvc.wsGetBranchListRequest request);
        
        // CODEGEN: Generating message contract since element name wsGetServiceTimeSlotListReq from namespace http://webservice.gms.com.my is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        DEWAXP.Foundation.Integration.QmsConfigSvc.wsGetServiceTimeSlotListResponse wsGetServiceTimeSlotList(DEWAXP.Foundation.Integration.QmsConfigSvc.wsGetServiceTimeSlotListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<DEWAXP.Foundation.Integration.QmsConfigSvc.wsGetServiceTimeSlotListResponse> wsGetServiceTimeSlotListAsync(DEWAXP.Foundation.Integration.QmsConfigSvc.wsGetServiceTimeSlotListRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class wsGetBranchListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="wsGetBranchList", Namespace="http://webservice.gms.com.my", Order=0)]
        public DEWAXP.Foundation.Integration.QmsConfigSvc.wsGetBranchListRequestBody Body;
        
        public wsGetBranchListRequest() {
        }
        
        public wsGetBranchListRequest(DEWAXP.Foundation.Integration.QmsConfigSvc.wsGetBranchListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservice.gms.com.my")]
    public partial class wsGetBranchListRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string wsGetBranchListReq;
        
        public wsGetBranchListRequestBody() {
        }
        
        public wsGetBranchListRequestBody(string wsGetBranchListReq) {
            this.wsGetBranchListReq = wsGetBranchListReq;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class wsGetBranchListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="wsGetBranchListResponse", Namespace="http://webservice.gms.com.my", Order=0)]
        public DEWAXP.Foundation.Integration.QmsConfigSvc.wsGetBranchListResponseBody Body;
        
        public wsGetBranchListResponse() {
        }
        
        public wsGetBranchListResponse(DEWAXP.Foundation.Integration.QmsConfigSvc.wsGetBranchListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservice.gms.com.my")]
    public partial class wsGetBranchListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string wsGetBranchListReturn;
        
        public wsGetBranchListResponseBody() {
        }
        
        public wsGetBranchListResponseBody(string wsGetBranchListReturn) {
            this.wsGetBranchListReturn = wsGetBranchListReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class wsGetServiceTimeSlotListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="wsGetServiceTimeSlotList", Namespace="http://webservice.gms.com.my", Order=0)]
        public DEWAXP.Foundation.Integration.QmsConfigSvc.wsGetServiceTimeSlotListRequestBody Body;
        
        public wsGetServiceTimeSlotListRequest() {
        }
        
        public wsGetServiceTimeSlotListRequest(DEWAXP.Foundation.Integration.QmsConfigSvc.wsGetServiceTimeSlotListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservice.gms.com.my")]
    public partial class wsGetServiceTimeSlotListRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string wsGetServiceTimeSlotListReq;
        
        public wsGetServiceTimeSlotListRequestBody() {
        }
        
        public wsGetServiceTimeSlotListRequestBody(string wsGetServiceTimeSlotListReq) {
            this.wsGetServiceTimeSlotListReq = wsGetServiceTimeSlotListReq;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class wsGetServiceTimeSlotListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="wsGetServiceTimeSlotListResponse", Namespace="http://webservice.gms.com.my", Order=0)]
        public DEWAXP.Foundation.Integration.QmsConfigSvc.wsGetServiceTimeSlotListResponseBody Body;
        
        public wsGetServiceTimeSlotListResponse() {
        }
        
        public wsGetServiceTimeSlotListResponse(DEWAXP.Foundation.Integration.QmsConfigSvc.wsGetServiceTimeSlotListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservice.gms.com.my")]
    public partial class wsGetServiceTimeSlotListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string wsGetServiceTimeSlotListReturn;
        
        public wsGetServiceTimeSlotListResponseBody() {
        }
        
        public wsGetServiceTimeSlotListResponseBody(string wsGetServiceTimeSlotListReturn) {
            this.wsGetServiceTimeSlotListReturn = wsGetServiceTimeSlotListReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface QmsConfigChannel : DEWAXP.Foundation.Integration.QmsConfigSvc.QmsConfig, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QmsConfigClient : System.ServiceModel.ClientBase<DEWAXP.Foundation.Integration.QmsConfigSvc.QmsConfig>, DEWAXP.Foundation.Integration.QmsConfigSvc.QmsConfig {
        
        public QmsConfigClient() {
        }
        
        public QmsConfigClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public QmsConfigClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QmsConfigClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QmsConfigClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DEWAXP.Foundation.Integration.QmsConfigSvc.wsGetBranchListResponse DEWAXP.Foundation.Integration.QmsConfigSvc.QmsConfig.wsGetBranchList(DEWAXP.Foundation.Integration.QmsConfigSvc.wsGetBranchListRequest request) {
            return base.Channel.wsGetBranchList(request);
        }
        
        public string wsGetBranchList(string wsGetBranchListReq) {
            DEWAXP.Foundation.Integration.QmsConfigSvc.wsGetBranchListRequest inValue = new DEWAXP.Foundation.Integration.QmsConfigSvc.wsGetBranchListRequest();
            inValue.Body = new DEWAXP.Foundation.Integration.QmsConfigSvc.wsGetBranchListRequestBody();
            inValue.Body.wsGetBranchListReq = wsGetBranchListReq;
            DEWAXP.Foundation.Integration.QmsConfigSvc.wsGetBranchListResponse retVal = ((DEWAXP.Foundation.Integration.QmsConfigSvc.QmsConfig)(this)).wsGetBranchList(inValue);
            return retVal.Body.wsGetBranchListReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DEWAXP.Foundation.Integration.QmsConfigSvc.wsGetBranchListResponse> DEWAXP.Foundation.Integration.QmsConfigSvc.QmsConfig.wsGetBranchListAsync(DEWAXP.Foundation.Integration.QmsConfigSvc.wsGetBranchListRequest request) {
            return base.Channel.wsGetBranchListAsync(request);
        }
        
        public System.Threading.Tasks.Task<DEWAXP.Foundation.Integration.QmsConfigSvc.wsGetBranchListResponse> wsGetBranchListAsync(string wsGetBranchListReq) {
            DEWAXP.Foundation.Integration.QmsConfigSvc.wsGetBranchListRequest inValue = new DEWAXP.Foundation.Integration.QmsConfigSvc.wsGetBranchListRequest();
            inValue.Body = new DEWAXP.Foundation.Integration.QmsConfigSvc.wsGetBranchListRequestBody();
            inValue.Body.wsGetBranchListReq = wsGetBranchListReq;
            return ((DEWAXP.Foundation.Integration.QmsConfigSvc.QmsConfig)(this)).wsGetBranchListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DEWAXP.Foundation.Integration.QmsConfigSvc.wsGetServiceTimeSlotListResponse DEWAXP.Foundation.Integration.QmsConfigSvc.QmsConfig.wsGetServiceTimeSlotList(DEWAXP.Foundation.Integration.QmsConfigSvc.wsGetServiceTimeSlotListRequest request) {
            return base.Channel.wsGetServiceTimeSlotList(request);
        }
        
        public string wsGetServiceTimeSlotList(string wsGetServiceTimeSlotListReq) {
            DEWAXP.Foundation.Integration.QmsConfigSvc.wsGetServiceTimeSlotListRequest inValue = new DEWAXP.Foundation.Integration.QmsConfigSvc.wsGetServiceTimeSlotListRequest();
            inValue.Body = new DEWAXP.Foundation.Integration.QmsConfigSvc.wsGetServiceTimeSlotListRequestBody();
            inValue.Body.wsGetServiceTimeSlotListReq = wsGetServiceTimeSlotListReq;
            DEWAXP.Foundation.Integration.QmsConfigSvc.wsGetServiceTimeSlotListResponse retVal = ((DEWAXP.Foundation.Integration.QmsConfigSvc.QmsConfig)(this)).wsGetServiceTimeSlotList(inValue);
            return retVal.Body.wsGetServiceTimeSlotListReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DEWAXP.Foundation.Integration.QmsConfigSvc.wsGetServiceTimeSlotListResponse> DEWAXP.Foundation.Integration.QmsConfigSvc.QmsConfig.wsGetServiceTimeSlotListAsync(DEWAXP.Foundation.Integration.QmsConfigSvc.wsGetServiceTimeSlotListRequest request) {
            return base.Channel.wsGetServiceTimeSlotListAsync(request);
        }
        
        public System.Threading.Tasks.Task<DEWAXP.Foundation.Integration.QmsConfigSvc.wsGetServiceTimeSlotListResponse> wsGetServiceTimeSlotListAsync(string wsGetServiceTimeSlotListReq) {
            DEWAXP.Foundation.Integration.QmsConfigSvc.wsGetServiceTimeSlotListRequest inValue = new DEWAXP.Foundation.Integration.QmsConfigSvc.wsGetServiceTimeSlotListRequest();
            inValue.Body = new DEWAXP.Foundation.Integration.QmsConfigSvc.wsGetServiceTimeSlotListRequestBody();
            inValue.Body.wsGetServiceTimeSlotListReq = wsGetServiceTimeSlotListReq;
            return ((DEWAXP.Foundation.Integration.QmsConfigSvc.QmsConfig)(this)).wsGetServiceTimeSlotListAsync(inValue);
        }
    }
}
