//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEWAXP.Foundation.Integration.VerificationcodeSvc {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dewa.gov.ae/hr/qrcode/")]
    public partial class Exception : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dewa.gov.ae/hr/qrcode/")]
    public partial class records : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string labelField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
                this.RaisePropertyChanged("label");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dewa.gov.ae/hr/qrcode/")]
    public partial class employeeData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private records recordsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public records records {
            get {
                return this.recordsField;
            }
            set {
                this.recordsField = value;
                this.RaisePropertyChanged("records");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dewa.gov.ae/hr/qrcode/")]
    public partial class qrDetails : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descriptionField;
        
        private employeeData employeedataField;
        
        private string idField;
        
        private string logmessagenumberField;
        
        private string lognumberField;
        
        private string messageField;
        
        private string message1Field;
        
        private string message2Field;
        
        private string message3Field;
        
        private string message4Field;
        
        private string numberField;
        
        private string responsecodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public employeeData employeedata {
            get {
                return this.employeedataField;
            }
            set {
                this.employeedataField = value;
                this.RaisePropertyChanged("employeedata");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string logmessagenumber {
            get {
                return this.logmessagenumberField;
            }
            set {
                this.logmessagenumberField = value;
                this.RaisePropertyChanged("logmessagenumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string lognumber {
            get {
                return this.lognumberField;
            }
            set {
                this.lognumberField = value;
                this.RaisePropertyChanged("lognumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string message1 {
            get {
                return this.message1Field;
            }
            set {
                this.message1Field = value;
                this.RaisePropertyChanged("message1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string message2 {
            get {
                return this.message2Field;
            }
            set {
                this.message2Field = value;
                this.RaisePropertyChanged("message2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string message3 {
            get {
                return this.message3Field;
            }
            set {
                this.message3Field = value;
                this.RaisePropertyChanged("message3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string message4 {
            get {
                return this.message4Field;
            }
            set {
                this.message4Field = value;
                this.RaisePropertyChanged("message4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
                this.RaisePropertyChanged("number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string responsecode {
            get {
                return this.responsecodeField;
            }
            set {
                this.responsecodeField = value;
                this.RaisePropertyChanged("responsecode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dewa.gov.ae/hr/qrcode/")]
    public partial class getQRCodeVerifiedResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private qrDetails returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public qrDetails @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dewa.gov.ae/hr/qrcode/")]
    public partial class qrParams : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string certificatetypeField;
        
        private string langField;
        
        private string pinnumberField;
        
        private string referencenumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string certificatetype {
            get {
                return this.certificatetypeField;
            }
            set {
                this.certificatetypeField = value;
                this.RaisePropertyChanged("certificatetype");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string lang {
            get {
                return this.langField;
            }
            set {
                this.langField = value;
                this.RaisePropertyChanged("lang");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string pinnumber {
            get {
                return this.pinnumberField;
            }
            set {
                this.pinnumberField = value;
                this.RaisePropertyChanged("pinnumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string referencenumber {
            get {
                return this.referencenumberField;
            }
            set {
                this.referencenumberField = value;
                this.RaisePropertyChanged("referencenumber");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dewa.gov.ae/hr/qrcode/")]
    public partial class getQRCodeVerified : object, System.ComponentModel.INotifyPropertyChanged {
        
        private qrParams qrparamsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public qrParams qrparams {
            get {
                return this.qrparamsField;
            }
            set {
                this.qrparamsField = value;
                this.RaisePropertyChanged("qrparams");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://dewa.gov.ae/hr/qrcode/", ConfigurationName="VerificationcodeSvc.QRCode")]
    public interface QRCode {
        
        // CODEGEN: Generating message contract since the operation getQRCodeVerified is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(DEWAXP.Foundation.Integration.VerificationcodeSvc.Exception), Action="", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DEWAXP.Foundation.Integration.VerificationcodeSvc.getQRCodeVerifiedResponse1 getQRCodeVerified(DEWAXP.Foundation.Integration.VerificationcodeSvc.getQRCodeVerifiedRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<DEWAXP.Foundation.Integration.VerificationcodeSvc.getQRCodeVerifiedResponse1> getQRCodeVerifiedAsync(DEWAXP.Foundation.Integration.VerificationcodeSvc.getQRCodeVerifiedRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getQRCodeVerifiedRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://dewa.gov.ae/hr/qrcode/", Order=0)]
        public DEWAXP.Foundation.Integration.VerificationcodeSvc.getQRCodeVerified getQRCodeVerified;
        
        public getQRCodeVerifiedRequest() {
        }
        
        public getQRCodeVerifiedRequest(DEWAXP.Foundation.Integration.VerificationcodeSvc.getQRCodeVerified getQRCodeVerified) {
            this.getQRCodeVerified = getQRCodeVerified;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getQRCodeVerifiedResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://dewa.gov.ae/hr/qrcode/", Order=0)]
        public DEWAXP.Foundation.Integration.VerificationcodeSvc.getQRCodeVerifiedResponse getQRCodeVerifiedResponse;
        
        public getQRCodeVerifiedResponse1() {
        }
        
        public getQRCodeVerifiedResponse1(DEWAXP.Foundation.Integration.VerificationcodeSvc.getQRCodeVerifiedResponse getQRCodeVerifiedResponse) {
            this.getQRCodeVerifiedResponse = getQRCodeVerifiedResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface QRCodeChannel : DEWAXP.Foundation.Integration.VerificationcodeSvc.QRCode, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QRCodeClient : System.ServiceModel.ClientBase<DEWAXP.Foundation.Integration.VerificationcodeSvc.QRCode>, DEWAXP.Foundation.Integration.VerificationcodeSvc.QRCode {
        
        public QRCodeClient() {
        }
        
        public QRCodeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public QRCodeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QRCodeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QRCodeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DEWAXP.Foundation.Integration.VerificationcodeSvc.getQRCodeVerifiedResponse1 DEWAXP.Foundation.Integration.VerificationcodeSvc.QRCode.getQRCodeVerified(DEWAXP.Foundation.Integration.VerificationcodeSvc.getQRCodeVerifiedRequest request) {
            return base.Channel.getQRCodeVerified(request);
        }
        
        public DEWAXP.Foundation.Integration.VerificationcodeSvc.getQRCodeVerifiedResponse getQRCodeVerified(DEWAXP.Foundation.Integration.VerificationcodeSvc.getQRCodeVerified getQRCodeVerified1) {
            DEWAXP.Foundation.Integration.VerificationcodeSvc.getQRCodeVerifiedRequest inValue = new DEWAXP.Foundation.Integration.VerificationcodeSvc.getQRCodeVerifiedRequest();
            inValue.getQRCodeVerified = getQRCodeVerified1;
            DEWAXP.Foundation.Integration.VerificationcodeSvc.getQRCodeVerifiedResponse1 retVal = ((DEWAXP.Foundation.Integration.VerificationcodeSvc.QRCode)(this)).getQRCodeVerified(inValue);
            return retVal.getQRCodeVerifiedResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DEWAXP.Foundation.Integration.VerificationcodeSvc.getQRCodeVerifiedResponse1> DEWAXP.Foundation.Integration.VerificationcodeSvc.QRCode.getQRCodeVerifiedAsync(DEWAXP.Foundation.Integration.VerificationcodeSvc.getQRCodeVerifiedRequest request) {
            return base.Channel.getQRCodeVerifiedAsync(request);
        }
        
        public System.Threading.Tasks.Task<DEWAXP.Foundation.Integration.VerificationcodeSvc.getQRCodeVerifiedResponse1> getQRCodeVerifiedAsync(DEWAXP.Foundation.Integration.VerificationcodeSvc.getQRCodeVerified getQRCodeVerified) {
            DEWAXP.Foundation.Integration.VerificationcodeSvc.getQRCodeVerifiedRequest inValue = new DEWAXP.Foundation.Integration.VerificationcodeSvc.getQRCodeVerifiedRequest();
            inValue.getQRCodeVerified = getQRCodeVerified;
            return ((DEWAXP.Foundation.Integration.VerificationcodeSvc.QRCode)(this)).getQRCodeVerifiedAsync(inValue);
        }
    }
}
