//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace DEWAXP.Foundation.Integration.HappinessSvc {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.myportal.dewa.gov.ae/employee/happiness/")]
    public partial class Exception : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        [field: NonSerialized]public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.myportal.dewa.gov.ae/employee/happiness/")]
    public partial class customerHappystatus : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string responsecodeField;
        
        private string uIMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string responsecode {
            get {
                return this.responsecodeField;
            }
            set {
                this.responsecodeField = value;
                this.RaisePropertyChanged("responsecode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string UIMessage {
            get {
                return this.uIMessageField;
            }
            set {
                this.uIMessageField = value;
                this.RaisePropertyChanged("UIMessage");
            }
        }
        
        [field: NonSerialized]public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.myportal.dewa.gov.ae/employee/happiness/")]
    public partial class SetCustomerHappinessSurveyResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private customerHappystatus returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public customerHappystatus @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        [field: NonSerialized]public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.myportal.dewa.gov.ae/employee/happiness/")]
    public partial class customerHappinessBean : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string choiceField;
        
        private string mobileField;
        
        private string serviceField;
        
        private string[] unhappyField;
        
        private string counternumberField;
        
        private string servicecenterField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string choice {
            get {
                return this.choiceField;
            }
            set {
                this.choiceField = value;
                this.RaisePropertyChanged("choice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string mobile {
            get {
                return this.mobileField;
            }
            set {
                this.mobileField = value;
                this.RaisePropertyChanged("mobile");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string service {
            get {
                return this.serviceField;
            }
            set {
                this.serviceField = value;
                this.RaisePropertyChanged("service");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("unhappy", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string[] unhappy {
            get {
                return this.unhappyField;
            }
            set {
                this.unhappyField = value;
                this.RaisePropertyChanged("unhappy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string counternumber {
            get {
                return this.counternumberField;
            }
            set {
                this.counternumberField = value;
                this.RaisePropertyChanged("counternumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string servicecenter {
            get {
                return this.servicecenterField;
            }
            set {
                this.servicecenterField = value;
                this.RaisePropertyChanged("servicecenter");
            }
        }
        
        [field: NonSerialized]public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.myportal.dewa.gov.ae/employee/happiness/")]
    public partial class SetCustomerHappinessSurvey : object, System.ComponentModel.INotifyPropertyChanged {
        
        private customerHappinessBean customerhappysurveyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public customerHappinessBean Customerhappysurvey {
            get {
                return this.customerhappysurveyField;
            }
            set {
                this.customerhappysurveyField = value;
                this.RaisePropertyChanged("Customerhappysurvey");
            }
        }
        
        [field: NonSerialized]public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.myportal.dewa.gov.ae/employee/happiness/")]
    public partial class setHappinessVoteDevice : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descriptionField;
        
        private string responseCodeField;
        
        private string uIMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string responseCode {
            get {
                return this.responseCodeField;
            }
            set {
                this.responseCodeField = value;
                this.RaisePropertyChanged("responseCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string UIMessage {
            get {
                return this.uIMessageField;
            }
            set {
                this.uIMessageField = value;
                this.RaisePropertyChanged("UIMessage");
            }
        }
        
        [field: NonSerialized]public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.myportal.dewa.gov.ae/employee/happiness/")]
    public partial class SetHappinessVoteDeviceResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private setHappinessVoteDevice returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public setHappinessVoteDevice @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        [field: NonSerialized]public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.myportal.dewa.gov.ae/employee/happiness/")]
    public partial class SetHappinessVoteDevice : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string deviceidField;
        
        private string voteField;
        
        private string langField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string deviceid {
            get {
                return this.deviceidField;
            }
            set {
                this.deviceidField = value;
                this.RaisePropertyChanged("deviceid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string vote {
            get {
                return this.voteField;
            }
            set {
                this.voteField = value;
                this.RaisePropertyChanged("vote");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string lang {
            get {
                return this.langField;
            }
            set {
                this.langField = value;
                this.RaisePropertyChanged("lang");
            }
        }
        
        [field: NonSerialized]public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.myportal.dewa.gov.ae/employee/happiness/")]
    public partial class setDeviceRegister : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descriptionField;
        
        private string responseCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string responseCode {
            get {
                return this.responseCodeField;
            }
            set {
                this.responseCodeField = value;
                this.RaisePropertyChanged("responseCode");
            }
        }
        
        [field: NonSerialized]public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.myportal.dewa.gov.ae/employee/happiness/")]
    public partial class SetDeviceRegisterResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private setDeviceRegister returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public setDeviceRegister @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        [field: NonSerialized]public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.myportal.dewa.gov.ae/employee/happiness/")]
    public partial class SetDeviceRegister : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string deviceidField;
        
        private string officeField;
        
        private string startdateField;
        
        private string enddateField;
        
        private string officenameField;
        
        private string devicetypeField;
        
        private string devicelocationField;
        
        private string devicefloorField;
        
        private string deviceassetnumberField;
        
        private string flagField;
        
        private string langField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string deviceid {
            get {
                return this.deviceidField;
            }
            set {
                this.deviceidField = value;
                this.RaisePropertyChanged("deviceid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string office {
            get {
                return this.officeField;
            }
            set {
                this.officeField = value;
                this.RaisePropertyChanged("office");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string startdate {
            get {
                return this.startdateField;
            }
            set {
                this.startdateField = value;
                this.RaisePropertyChanged("startdate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string enddate {
            get {
                return this.enddateField;
            }
            set {
                this.enddateField = value;
                this.RaisePropertyChanged("enddate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string officename {
            get {
                return this.officenameField;
            }
            set {
                this.officenameField = value;
                this.RaisePropertyChanged("officename");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string devicetype {
            get {
                return this.devicetypeField;
            }
            set {
                this.devicetypeField = value;
                this.RaisePropertyChanged("devicetype");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string devicelocation {
            get {
                return this.devicelocationField;
            }
            set {
                this.devicelocationField = value;
                this.RaisePropertyChanged("devicelocation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string devicefloor {
            get {
                return this.devicefloorField;
            }
            set {
                this.devicefloorField = value;
                this.RaisePropertyChanged("devicefloor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string deviceassetnumber {
            get {
                return this.deviceassetnumberField;
            }
            set {
                this.deviceassetnumberField = value;
                this.RaisePropertyChanged("deviceassetnumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string flag {
            get {
                return this.flagField;
            }
            set {
                this.flagField = value;
                this.RaisePropertyChanged("flag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string lang {
            get {
                return this.langField;
            }
            set {
                this.langField = value;
                this.RaisePropertyChanged("lang");
            }
        }
        
        [field: NonSerialized]public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.myportal.dewa.gov.ae/employee/happiness/")]
    public partial class deviceDetails : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string deviceAssetNumberField;
        
        private string deviceFloorField;
        
        private string deviceIDField;
        
        private string deviceLocationField;
        
        private string deviceTypeField;
        
        private string endDateField;
        
        private string flagField;
        
        private string officeField;
        
        private string officeNameField;
        
        private string startDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string deviceAssetNumber {
            get {
                return this.deviceAssetNumberField;
            }
            set {
                this.deviceAssetNumberField = value;
                this.RaisePropertyChanged("deviceAssetNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string deviceFloor {
            get {
                return this.deviceFloorField;
            }
            set {
                this.deviceFloorField = value;
                this.RaisePropertyChanged("deviceFloor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string deviceID {
            get {
                return this.deviceIDField;
            }
            set {
                this.deviceIDField = value;
                this.RaisePropertyChanged("deviceID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string deviceLocation {
            get {
                return this.deviceLocationField;
            }
            set {
                this.deviceLocationField = value;
                this.RaisePropertyChanged("deviceLocation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string deviceType {
            get {
                return this.deviceTypeField;
            }
            set {
                this.deviceTypeField = value;
                this.RaisePropertyChanged("deviceType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string endDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
                this.RaisePropertyChanged("endDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string flag {
            get {
                return this.flagField;
            }
            set {
                this.flagField = value;
                this.RaisePropertyChanged("flag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string office {
            get {
                return this.officeField;
            }
            set {
                this.officeField = value;
                this.RaisePropertyChanged("office");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string officeName {
            get {
                return this.officeNameField;
            }
            set {
                this.officeNameField = value;
                this.RaisePropertyChanged("officeName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string startDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
                this.RaisePropertyChanged("startDate");
            }
        }
        
        [field: NonSerialized]public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.myportal.dewa.gov.ae/employee/happiness/")]
    public partial class getDeviceDetails : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descriptionField;
        
        private deviceDetails[] deviceListField;
        
        private string responseCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("deviceList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public deviceDetails[] deviceList {
            get {
                return this.deviceListField;
            }
            set {
                this.deviceListField = value;
                this.RaisePropertyChanged("deviceList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string responseCode {
            get {
                return this.responseCodeField;
            }
            set {
                this.responseCodeField = value;
                this.RaisePropertyChanged("responseCode");
            }
        }
        
        [field: NonSerialized]public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.myportal.dewa.gov.ae/employee/happiness/")]
    public partial class GetDeviceDetailsResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private getDeviceDetails returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public getDeviceDetails @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        [field: NonSerialized]public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.myportal.dewa.gov.ae/employee/happiness/")]
    public partial class GetDeviceDetails : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string deviceidField;
        
        private string langField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string deviceid {
            get {
                return this.deviceidField;
            }
            set {
                this.deviceidField = value;
                this.RaisePropertyChanged("deviceid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string lang {
            get {
                return this.langField;
            }
            set {
                this.langField = value;
                this.RaisePropertyChanged("lang");
            }
        }
        
        [field: NonSerialized]public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.myportal.dewa.gov.ae/employee/happiness/")]
    public partial class SetEmployeeHappinessVoteResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        [field: NonSerialized]public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.myportal.dewa.gov.ae/employee/happiness/")]
    public partial class SetEmployeeHappinessVote : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idnumberField;
        
        private string voteField;
        
        private string remarksField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string idnumber {
            get {
                return this.idnumberField;
            }
            set {
                this.idnumberField = value;
                this.RaisePropertyChanged("idnumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string vote {
            get {
                return this.voteField;
            }
            set {
                this.voteField = value;
                this.RaisePropertyChanged("vote");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string remarks {
            get {
                return this.remarksField;
            }
            set {
                this.remarksField = value;
                this.RaisePropertyChanged("remarks");
            }
        }
        
        [field: NonSerialized]public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.myportal.dewa.gov.ae/employee/happiness/", ConfigurationName="HappinessSvc.Config")]
    public interface Config {
        
        // CODEGEN: Generating message contract since the operation SetEmployeeHappinessVote is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DEWAXP.Foundation.Integration.HappinessSvc.SetEmployeeHappinessVoteResponse1 SetEmployeeHappinessVote(DEWAXP.Foundation.Integration.HappinessSvc.SetEmployeeHappinessVoteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<DEWAXP.Foundation.Integration.HappinessSvc.SetEmployeeHappinessVoteResponse1> SetEmployeeHappinessVoteAsync(DEWAXP.Foundation.Integration.HappinessSvc.SetEmployeeHappinessVoteRequest request);
        
        // CODEGEN: Generating message contract since the operation GetDeviceDetails is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DEWAXP.Foundation.Integration.HappinessSvc.GetDeviceDetailsResponse1 GetDeviceDetails(DEWAXP.Foundation.Integration.HappinessSvc.GetDeviceDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<DEWAXP.Foundation.Integration.HappinessSvc.GetDeviceDetailsResponse1> GetDeviceDetailsAsync(DEWAXP.Foundation.Integration.HappinessSvc.GetDeviceDetailsRequest request);
        
        // CODEGEN: Generating message contract since the operation SetDeviceRegister is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DEWAXP.Foundation.Integration.HappinessSvc.SetDeviceRegisterResponse1 SetDeviceRegister(DEWAXP.Foundation.Integration.HappinessSvc.SetDeviceRegisterRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<DEWAXP.Foundation.Integration.HappinessSvc.SetDeviceRegisterResponse1> SetDeviceRegisterAsync(DEWAXP.Foundation.Integration.HappinessSvc.SetDeviceRegisterRequest request);
        
        // CODEGEN: Generating message contract since the operation SetHappinessVoteDevice is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DEWAXP.Foundation.Integration.HappinessSvc.SetHappinessVoteDeviceResponse1 SetHappinessVoteDevice(DEWAXP.Foundation.Integration.HappinessSvc.SetHappinessVoteDeviceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<DEWAXP.Foundation.Integration.HappinessSvc.SetHappinessVoteDeviceResponse1> SetHappinessVoteDeviceAsync(DEWAXP.Foundation.Integration.HappinessSvc.SetHappinessVoteDeviceRequest request);
        
        // CODEGEN: Generating message contract since the operation SetCustomerHappinessSurvey is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(DEWAXP.Foundation.Integration.HappinessSvc.Exception), Action="", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DEWAXP.Foundation.Integration.HappinessSvc.SetCustomerHappinessSurveyResponse1 SetCustomerHappinessSurvey(DEWAXP.Foundation.Integration.HappinessSvc.SetCustomerHappinessSurveyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<DEWAXP.Foundation.Integration.HappinessSvc.SetCustomerHappinessSurveyResponse1> SetCustomerHappinessSurveyAsync(DEWAXP.Foundation.Integration.HappinessSvc.SetCustomerHappinessSurveyRequest request);
        
        // CODEGEN: Generating message contract since the operation GetCustHappinessSurveyQuestions is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DEWAXP.Foundation.Integration.HappinessSvc.GetCustHappinessSurveyQuestionsResponse1 GetCustHappinessSurveyQuestions(DEWAXP.Foundation.Integration.HappinessSvc.GetCustHappinessSurveyQuestionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<DEWAXP.Foundation.Integration.HappinessSvc.GetCustHappinessSurveyQuestionsResponse1> GetCustHappinessSurveyQuestionsAsync(DEWAXP.Foundation.Integration.HappinessSvc.GetCustHappinessSurveyQuestionsRequest request);
        
        // CODEGEN: Generating message contract since the operation SetCustHappinessSurveyAnswers is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DEWAXP.Foundation.Integration.HappinessSvc.SetCustHappinessSurveyAnswersResponse1 SetCustHappinessSurveyAnswers(DEWAXP.Foundation.Integration.HappinessSvc.SetCustHappinessSurveyAnswersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<DEWAXP.Foundation.Integration.HappinessSvc.SetCustHappinessSurveyAnswersResponse1> SetCustHappinessSurveyAnswersAsync(DEWAXP.Foundation.Integration.HappinessSvc.SetCustHappinessSurveyAnswersRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetEmployeeHappinessVoteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.myportal.dewa.gov.ae/employee/happiness/", Order=0)]
        public DEWAXP.Foundation.Integration.HappinessSvc.SetEmployeeHappinessVote SetEmployeeHappinessVote;
        
        public SetEmployeeHappinessVoteRequest() {
        }
        
        public SetEmployeeHappinessVoteRequest(DEWAXP.Foundation.Integration.HappinessSvc.SetEmployeeHappinessVote SetEmployeeHappinessVote) {
            this.SetEmployeeHappinessVote = SetEmployeeHappinessVote;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetEmployeeHappinessVoteResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.myportal.dewa.gov.ae/employee/happiness/", Order=0)]
        public DEWAXP.Foundation.Integration.HappinessSvc.SetEmployeeHappinessVoteResponse SetEmployeeHappinessVoteResponse;
        
        public SetEmployeeHappinessVoteResponse1() {
        }
        
        public SetEmployeeHappinessVoteResponse1(DEWAXP.Foundation.Integration.HappinessSvc.SetEmployeeHappinessVoteResponse SetEmployeeHappinessVoteResponse) {
            this.SetEmployeeHappinessVoteResponse = SetEmployeeHappinessVoteResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDeviceDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.myportal.dewa.gov.ae/employee/happiness/", Order=0)]
        public DEWAXP.Foundation.Integration.HappinessSvc.GetDeviceDetails GetDeviceDetails;
        
        public GetDeviceDetailsRequest() {
        }
        
        public GetDeviceDetailsRequest(DEWAXP.Foundation.Integration.HappinessSvc.GetDeviceDetails GetDeviceDetails) {
            this.GetDeviceDetails = GetDeviceDetails;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDeviceDetailsResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.myportal.dewa.gov.ae/employee/happiness/", Order=0)]
        public DEWAXP.Foundation.Integration.HappinessSvc.GetDeviceDetailsResponse GetDeviceDetailsResponse;
        
        public GetDeviceDetailsResponse1() {
        }
        
        public GetDeviceDetailsResponse1(DEWAXP.Foundation.Integration.HappinessSvc.GetDeviceDetailsResponse GetDeviceDetailsResponse) {
            this.GetDeviceDetailsResponse = GetDeviceDetailsResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetDeviceRegisterRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.myportal.dewa.gov.ae/employee/happiness/", Order=0)]
        public DEWAXP.Foundation.Integration.HappinessSvc.SetDeviceRegister SetDeviceRegister;
        
        public SetDeviceRegisterRequest() {
        }
        
        public SetDeviceRegisterRequest(DEWAXP.Foundation.Integration.HappinessSvc.SetDeviceRegister SetDeviceRegister) {
            this.SetDeviceRegister = SetDeviceRegister;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetDeviceRegisterResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.myportal.dewa.gov.ae/employee/happiness/", Order=0)]
        public DEWAXP.Foundation.Integration.HappinessSvc.SetDeviceRegisterResponse SetDeviceRegisterResponse;
        
        public SetDeviceRegisterResponse1() {
        }
        
        public SetDeviceRegisterResponse1(DEWAXP.Foundation.Integration.HappinessSvc.SetDeviceRegisterResponse SetDeviceRegisterResponse) {
            this.SetDeviceRegisterResponse = SetDeviceRegisterResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetHappinessVoteDeviceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.myportal.dewa.gov.ae/employee/happiness/", Order=0)]
        public DEWAXP.Foundation.Integration.HappinessSvc.SetHappinessVoteDevice SetHappinessVoteDevice;
        
        public SetHappinessVoteDeviceRequest() {
        }
        
        public SetHappinessVoteDeviceRequest(DEWAXP.Foundation.Integration.HappinessSvc.SetHappinessVoteDevice SetHappinessVoteDevice) {
            this.SetHappinessVoteDevice = SetHappinessVoteDevice;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetHappinessVoteDeviceResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.myportal.dewa.gov.ae/employee/happiness/", Order=0)]
        public DEWAXP.Foundation.Integration.HappinessSvc.SetHappinessVoteDeviceResponse SetHappinessVoteDeviceResponse;
        
        public SetHappinessVoteDeviceResponse1() {
        }
        
        public SetHappinessVoteDeviceResponse1(DEWAXP.Foundation.Integration.HappinessSvc.SetHappinessVoteDeviceResponse SetHappinessVoteDeviceResponse) {
            this.SetHappinessVoteDeviceResponse = SetHappinessVoteDeviceResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetCustomerHappinessSurveyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.myportal.dewa.gov.ae/employee/happiness/", Order=0)]
        public DEWAXP.Foundation.Integration.HappinessSvc.SetCustomerHappinessSurvey SetCustomerHappinessSurvey;
        
        public SetCustomerHappinessSurveyRequest() {
        }
        
        public SetCustomerHappinessSurveyRequest(DEWAXP.Foundation.Integration.HappinessSvc.SetCustomerHappinessSurvey SetCustomerHappinessSurvey) {
            this.SetCustomerHappinessSurvey = SetCustomerHappinessSurvey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetCustomerHappinessSurveyResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.myportal.dewa.gov.ae/employee/happiness/", Order=0)]
        public DEWAXP.Foundation.Integration.HappinessSvc.SetCustomerHappinessSurveyResponse SetCustomerHappinessSurveyResponse;
        
        public SetCustomerHappinessSurveyResponse1() {
        }
        
        public SetCustomerHappinessSurveyResponse1(DEWAXP.Foundation.Integration.HappinessSvc.SetCustomerHappinessSurveyResponse SetCustomerHappinessSurveyResponse) {
            this.SetCustomerHappinessSurveyResponse = SetCustomerHappinessSurveyResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.myportal.dewa.gov.ae/employee/happiness/")]
    public partial class GetCustHappinessSurveyQuestions : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string surveyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string survey {
            get {
                return this.surveyField;
            }
            set {
                this.surveyField = value;
                this.RaisePropertyChanged("survey");
            }
        }
        
        [field: NonSerialized]public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.myportal.dewa.gov.ae/employee/happiness/")]
    public partial class GetCustHappinessSurveyQuestionsResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        [field: NonSerialized]public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCustHappinessSurveyQuestionsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.myportal.dewa.gov.ae/employee/happiness/", Order=0)]
        public DEWAXP.Foundation.Integration.HappinessSvc.GetCustHappinessSurveyQuestions GetCustHappinessSurveyQuestions;
        
        public GetCustHappinessSurveyQuestionsRequest() {
        }
        
        public GetCustHappinessSurveyQuestionsRequest(DEWAXP.Foundation.Integration.HappinessSvc.GetCustHappinessSurveyQuestions GetCustHappinessSurveyQuestions) {
            this.GetCustHappinessSurveyQuestions = GetCustHappinessSurveyQuestions;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCustHappinessSurveyQuestionsResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.myportal.dewa.gov.ae/employee/happiness/", Order=0)]
        public DEWAXP.Foundation.Integration.HappinessSvc.GetCustHappinessSurveyQuestionsResponse GetCustHappinessSurveyQuestionsResponse;
        
        public GetCustHappinessSurveyQuestionsResponse1() {
        }
        
        public GetCustHappinessSurveyQuestionsResponse1(DEWAXP.Foundation.Integration.HappinessSvc.GetCustHappinessSurveyQuestionsResponse GetCustHappinessSurveyQuestionsResponse) {
            this.GetCustHappinessSurveyQuestionsResponse = GetCustHappinessSurveyQuestionsResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.myportal.dewa.gov.ae/employee/happiness/")]
    public partial class SetCustHappinessSurveyAnswers : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string surveyField;
        
        private string referenceNumberField;
        
        private surveyAnswer[] customerSurveyAnswersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string survey {
            get {
                return this.surveyField;
            }
            set {
                this.surveyField = value;
                this.RaisePropertyChanged("survey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string referenceNumber {
            get {
                return this.referenceNumberField;
            }
            set {
                this.referenceNumberField = value;
                this.RaisePropertyChanged("referenceNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("answer", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public surveyAnswer[] customerSurveyAnswers {
            get {
                return this.customerSurveyAnswersField;
            }
            set {
                this.customerSurveyAnswersField = value;
                this.RaisePropertyChanged("customerSurveyAnswers");
            }
        }
        
        [field: NonSerialized]public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.myportal.dewa.gov.ae/employee/happiness/")]
    public partial class surveyAnswer : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string answerNumberField;
        
        private string arabicField;
        
        private string englishField;
        
        private string questionNumberField;
        
        private string surveyField;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string answerNumber {
            get {
                return this.answerNumberField;
            }
            set {
                this.answerNumberField = value;
                this.RaisePropertyChanged("answerNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string arabic {
            get {
                return this.arabicField;
            }
            set {
                this.arabicField = value;
                this.RaisePropertyChanged("arabic");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string english {
            get {
                return this.englishField;
            }
            set {
                this.englishField = value;
                this.RaisePropertyChanged("english");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string questionNumber {
            get {
                return this.questionNumberField;
            }
            set {
                this.questionNumberField = value;
                this.RaisePropertyChanged("questionNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string survey {
            get {
                return this.surveyField;
            }
            set {
                this.surveyField = value;
                this.RaisePropertyChanged("survey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        [field: NonSerialized]public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.myportal.dewa.gov.ae/employee/happiness/")]
    public partial class SetCustHappinessSurveyAnswersResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        [field: NonSerialized]public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetCustHappinessSurveyAnswersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.myportal.dewa.gov.ae/employee/happiness/", Order=0)]
        public DEWAXP.Foundation.Integration.HappinessSvc.SetCustHappinessSurveyAnswers SetCustHappinessSurveyAnswers;
        
        public SetCustHappinessSurveyAnswersRequest() {
        }
        
        public SetCustHappinessSurveyAnswersRequest(DEWAXP.Foundation.Integration.HappinessSvc.SetCustHappinessSurveyAnswers SetCustHappinessSurveyAnswers) {
            this.SetCustHappinessSurveyAnswers = SetCustHappinessSurveyAnswers;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetCustHappinessSurveyAnswersResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.myportal.dewa.gov.ae/employee/happiness/", Order=0)]
        public DEWAXP.Foundation.Integration.HappinessSvc.SetCustHappinessSurveyAnswersResponse SetCustHappinessSurveyAnswersResponse;
        
        public SetCustHappinessSurveyAnswersResponse1() {
        }
        
        public SetCustHappinessSurveyAnswersResponse1(DEWAXP.Foundation.Integration.HappinessSvc.SetCustHappinessSurveyAnswersResponse SetCustHappinessSurveyAnswersResponse) {
            this.SetCustHappinessSurveyAnswersResponse = SetCustHappinessSurveyAnswersResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ConfigChannel : DEWAXP.Foundation.Integration.HappinessSvc.Config, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConfigClient : System.ServiceModel.ClientBase<DEWAXP.Foundation.Integration.HappinessSvc.Config>, DEWAXP.Foundation.Integration.HappinessSvc.Config {
        
        public ConfigClient() {
        }
        
        public ConfigClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConfigClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConfigClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConfigClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DEWAXP.Foundation.Integration.HappinessSvc.SetEmployeeHappinessVoteResponse1 DEWAXP.Foundation.Integration.HappinessSvc.Config.SetEmployeeHappinessVote(DEWAXP.Foundation.Integration.HappinessSvc.SetEmployeeHappinessVoteRequest request) {
            return base.Channel.SetEmployeeHappinessVote(request);
        }
        
        public DEWAXP.Foundation.Integration.HappinessSvc.SetEmployeeHappinessVoteResponse SetEmployeeHappinessVote(DEWAXP.Foundation.Integration.HappinessSvc.SetEmployeeHappinessVote SetEmployeeHappinessVote1) {
            DEWAXP.Foundation.Integration.HappinessSvc.SetEmployeeHappinessVoteRequest inValue = new DEWAXP.Foundation.Integration.HappinessSvc.SetEmployeeHappinessVoteRequest();
            inValue.SetEmployeeHappinessVote = SetEmployeeHappinessVote1;
            DEWAXP.Foundation.Integration.HappinessSvc.SetEmployeeHappinessVoteResponse1 retVal = ((DEWAXP.Foundation.Integration.HappinessSvc.Config)(this)).SetEmployeeHappinessVote(inValue);
            return retVal.SetEmployeeHappinessVoteResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DEWAXP.Foundation.Integration.HappinessSvc.SetEmployeeHappinessVoteResponse1> DEWAXP.Foundation.Integration.HappinessSvc.Config.SetEmployeeHappinessVoteAsync(DEWAXP.Foundation.Integration.HappinessSvc.SetEmployeeHappinessVoteRequest request) {
            return base.Channel.SetEmployeeHappinessVoteAsync(request);
        }
        
        public System.Threading.Tasks.Task<DEWAXP.Foundation.Integration.HappinessSvc.SetEmployeeHappinessVoteResponse1> SetEmployeeHappinessVoteAsync(DEWAXP.Foundation.Integration.HappinessSvc.SetEmployeeHappinessVote SetEmployeeHappinessVote) {
            DEWAXP.Foundation.Integration.HappinessSvc.SetEmployeeHappinessVoteRequest inValue = new DEWAXP.Foundation.Integration.HappinessSvc.SetEmployeeHappinessVoteRequest();
            inValue.SetEmployeeHappinessVote = SetEmployeeHappinessVote;
            return ((DEWAXP.Foundation.Integration.HappinessSvc.Config)(this)).SetEmployeeHappinessVoteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DEWAXP.Foundation.Integration.HappinessSvc.GetDeviceDetailsResponse1 DEWAXP.Foundation.Integration.HappinessSvc.Config.GetDeviceDetails(DEWAXP.Foundation.Integration.HappinessSvc.GetDeviceDetailsRequest request) {
            return base.Channel.GetDeviceDetails(request);
        }
        
        public DEWAXP.Foundation.Integration.HappinessSvc.GetDeviceDetailsResponse GetDeviceDetails(DEWAXP.Foundation.Integration.HappinessSvc.GetDeviceDetails GetDeviceDetails1) {
            DEWAXP.Foundation.Integration.HappinessSvc.GetDeviceDetailsRequest inValue = new DEWAXP.Foundation.Integration.HappinessSvc.GetDeviceDetailsRequest();
            inValue.GetDeviceDetails = GetDeviceDetails1;
            DEWAXP.Foundation.Integration.HappinessSvc.GetDeviceDetailsResponse1 retVal = ((DEWAXP.Foundation.Integration.HappinessSvc.Config)(this)).GetDeviceDetails(inValue);
            return retVal.GetDeviceDetailsResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DEWAXP.Foundation.Integration.HappinessSvc.GetDeviceDetailsResponse1> DEWAXP.Foundation.Integration.HappinessSvc.Config.GetDeviceDetailsAsync(DEWAXP.Foundation.Integration.HappinessSvc.GetDeviceDetailsRequest request) {
            return base.Channel.GetDeviceDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<DEWAXP.Foundation.Integration.HappinessSvc.GetDeviceDetailsResponse1> GetDeviceDetailsAsync(DEWAXP.Foundation.Integration.HappinessSvc.GetDeviceDetails GetDeviceDetails) {
            DEWAXP.Foundation.Integration.HappinessSvc.GetDeviceDetailsRequest inValue = new DEWAXP.Foundation.Integration.HappinessSvc.GetDeviceDetailsRequest();
            inValue.GetDeviceDetails = GetDeviceDetails;
            return ((DEWAXP.Foundation.Integration.HappinessSvc.Config)(this)).GetDeviceDetailsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DEWAXP.Foundation.Integration.HappinessSvc.SetDeviceRegisterResponse1 DEWAXP.Foundation.Integration.HappinessSvc.Config.SetDeviceRegister(DEWAXP.Foundation.Integration.HappinessSvc.SetDeviceRegisterRequest request) {
            return base.Channel.SetDeviceRegister(request);
        }
        
        public DEWAXP.Foundation.Integration.HappinessSvc.SetDeviceRegisterResponse SetDeviceRegister(DEWAXP.Foundation.Integration.HappinessSvc.SetDeviceRegister SetDeviceRegister1) {
            DEWAXP.Foundation.Integration.HappinessSvc.SetDeviceRegisterRequest inValue = new DEWAXP.Foundation.Integration.HappinessSvc.SetDeviceRegisterRequest();
            inValue.SetDeviceRegister = SetDeviceRegister1;
            DEWAXP.Foundation.Integration.HappinessSvc.SetDeviceRegisterResponse1 retVal = ((DEWAXP.Foundation.Integration.HappinessSvc.Config)(this)).SetDeviceRegister(inValue);
            return retVal.SetDeviceRegisterResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DEWAXP.Foundation.Integration.HappinessSvc.SetDeviceRegisterResponse1> DEWAXP.Foundation.Integration.HappinessSvc.Config.SetDeviceRegisterAsync(DEWAXP.Foundation.Integration.HappinessSvc.SetDeviceRegisterRequest request) {
            return base.Channel.SetDeviceRegisterAsync(request);
        }
        
        public System.Threading.Tasks.Task<DEWAXP.Foundation.Integration.HappinessSvc.SetDeviceRegisterResponse1> SetDeviceRegisterAsync(DEWAXP.Foundation.Integration.HappinessSvc.SetDeviceRegister SetDeviceRegister) {
            DEWAXP.Foundation.Integration.HappinessSvc.SetDeviceRegisterRequest inValue = new DEWAXP.Foundation.Integration.HappinessSvc.SetDeviceRegisterRequest();
            inValue.SetDeviceRegister = SetDeviceRegister;
            return ((DEWAXP.Foundation.Integration.HappinessSvc.Config)(this)).SetDeviceRegisterAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DEWAXP.Foundation.Integration.HappinessSvc.SetHappinessVoteDeviceResponse1 DEWAXP.Foundation.Integration.HappinessSvc.Config.SetHappinessVoteDevice(DEWAXP.Foundation.Integration.HappinessSvc.SetHappinessVoteDeviceRequest request) {
            return base.Channel.SetHappinessVoteDevice(request);
        }
        
        public DEWAXP.Foundation.Integration.HappinessSvc.SetHappinessVoteDeviceResponse SetHappinessVoteDevice(DEWAXP.Foundation.Integration.HappinessSvc.SetHappinessVoteDevice SetHappinessVoteDevice1) {
            DEWAXP.Foundation.Integration.HappinessSvc.SetHappinessVoteDeviceRequest inValue = new DEWAXP.Foundation.Integration.HappinessSvc.SetHappinessVoteDeviceRequest();
            inValue.SetHappinessVoteDevice = SetHappinessVoteDevice1;
            DEWAXP.Foundation.Integration.HappinessSvc.SetHappinessVoteDeviceResponse1 retVal = ((DEWAXP.Foundation.Integration.HappinessSvc.Config)(this)).SetHappinessVoteDevice(inValue);
            return retVal.SetHappinessVoteDeviceResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DEWAXP.Foundation.Integration.HappinessSvc.SetHappinessVoteDeviceResponse1> DEWAXP.Foundation.Integration.HappinessSvc.Config.SetHappinessVoteDeviceAsync(DEWAXP.Foundation.Integration.HappinessSvc.SetHappinessVoteDeviceRequest request) {
            return base.Channel.SetHappinessVoteDeviceAsync(request);
        }
        
        public System.Threading.Tasks.Task<DEWAXP.Foundation.Integration.HappinessSvc.SetHappinessVoteDeviceResponse1> SetHappinessVoteDeviceAsync(DEWAXP.Foundation.Integration.HappinessSvc.SetHappinessVoteDevice SetHappinessVoteDevice) {
            DEWAXP.Foundation.Integration.HappinessSvc.SetHappinessVoteDeviceRequest inValue = new DEWAXP.Foundation.Integration.HappinessSvc.SetHappinessVoteDeviceRequest();
            inValue.SetHappinessVoteDevice = SetHappinessVoteDevice;
            return ((DEWAXP.Foundation.Integration.HappinessSvc.Config)(this)).SetHappinessVoteDeviceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DEWAXP.Foundation.Integration.HappinessSvc.SetCustomerHappinessSurveyResponse1 DEWAXP.Foundation.Integration.HappinessSvc.Config.SetCustomerHappinessSurvey(DEWAXP.Foundation.Integration.HappinessSvc.SetCustomerHappinessSurveyRequest request) {
            return base.Channel.SetCustomerHappinessSurvey(request);
        }
        
        public DEWAXP.Foundation.Integration.HappinessSvc.SetCustomerHappinessSurveyResponse SetCustomerHappinessSurvey(DEWAXP.Foundation.Integration.HappinessSvc.SetCustomerHappinessSurvey SetCustomerHappinessSurvey1) {
            DEWAXP.Foundation.Integration.HappinessSvc.SetCustomerHappinessSurveyRequest inValue = new DEWAXP.Foundation.Integration.HappinessSvc.SetCustomerHappinessSurveyRequest();
            inValue.SetCustomerHappinessSurvey = SetCustomerHappinessSurvey1;
            DEWAXP.Foundation.Integration.HappinessSvc.SetCustomerHappinessSurveyResponse1 retVal = ((DEWAXP.Foundation.Integration.HappinessSvc.Config)(this)).SetCustomerHappinessSurvey(inValue);
            return retVal.SetCustomerHappinessSurveyResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DEWAXP.Foundation.Integration.HappinessSvc.SetCustomerHappinessSurveyResponse1> DEWAXP.Foundation.Integration.HappinessSvc.Config.SetCustomerHappinessSurveyAsync(DEWAXP.Foundation.Integration.HappinessSvc.SetCustomerHappinessSurveyRequest request) {
            return base.Channel.SetCustomerHappinessSurveyAsync(request);
        }
        
        public System.Threading.Tasks.Task<DEWAXP.Foundation.Integration.HappinessSvc.SetCustomerHappinessSurveyResponse1> SetCustomerHappinessSurveyAsync(DEWAXP.Foundation.Integration.HappinessSvc.SetCustomerHappinessSurvey SetCustomerHappinessSurvey) {
            DEWAXP.Foundation.Integration.HappinessSvc.SetCustomerHappinessSurveyRequest inValue = new DEWAXP.Foundation.Integration.HappinessSvc.SetCustomerHappinessSurveyRequest();
            inValue.SetCustomerHappinessSurvey = SetCustomerHappinessSurvey;
            return ((DEWAXP.Foundation.Integration.HappinessSvc.Config)(this)).SetCustomerHappinessSurveyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DEWAXP.Foundation.Integration.HappinessSvc.GetCustHappinessSurveyQuestionsResponse1 DEWAXP.Foundation.Integration.HappinessSvc.Config.GetCustHappinessSurveyQuestions(DEWAXP.Foundation.Integration.HappinessSvc.GetCustHappinessSurveyQuestionsRequest request) {
            return base.Channel.GetCustHappinessSurveyQuestions(request);
        }
        
        public DEWAXP.Foundation.Integration.HappinessSvc.GetCustHappinessSurveyQuestionsResponse GetCustHappinessSurveyQuestions(DEWAXP.Foundation.Integration.HappinessSvc.GetCustHappinessSurveyQuestions GetCustHappinessSurveyQuestions1) {
            DEWAXP.Foundation.Integration.HappinessSvc.GetCustHappinessSurveyQuestionsRequest inValue = new DEWAXP.Foundation.Integration.HappinessSvc.GetCustHappinessSurveyQuestionsRequest();
            inValue.GetCustHappinessSurveyQuestions = GetCustHappinessSurveyQuestions1;
            DEWAXP.Foundation.Integration.HappinessSvc.GetCustHappinessSurveyQuestionsResponse1 retVal = ((DEWAXP.Foundation.Integration.HappinessSvc.Config)(this)).GetCustHappinessSurveyQuestions(inValue);
            return retVal.GetCustHappinessSurveyQuestionsResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DEWAXP.Foundation.Integration.HappinessSvc.GetCustHappinessSurveyQuestionsResponse1> DEWAXP.Foundation.Integration.HappinessSvc.Config.GetCustHappinessSurveyQuestionsAsync(DEWAXP.Foundation.Integration.HappinessSvc.GetCustHappinessSurveyQuestionsRequest request) {
            return base.Channel.GetCustHappinessSurveyQuestionsAsync(request);
        }
        
        public System.Threading.Tasks.Task<DEWAXP.Foundation.Integration.HappinessSvc.GetCustHappinessSurveyQuestionsResponse1> GetCustHappinessSurveyQuestionsAsync(DEWAXP.Foundation.Integration.HappinessSvc.GetCustHappinessSurveyQuestions GetCustHappinessSurveyQuestions) {
            DEWAXP.Foundation.Integration.HappinessSvc.GetCustHappinessSurveyQuestionsRequest inValue = new DEWAXP.Foundation.Integration.HappinessSvc.GetCustHappinessSurveyQuestionsRequest();
            inValue.GetCustHappinessSurveyQuestions = GetCustHappinessSurveyQuestions;
            return ((DEWAXP.Foundation.Integration.HappinessSvc.Config)(this)).GetCustHappinessSurveyQuestionsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DEWAXP.Foundation.Integration.HappinessSvc.SetCustHappinessSurveyAnswersResponse1 DEWAXP.Foundation.Integration.HappinessSvc.Config.SetCustHappinessSurveyAnswers(DEWAXP.Foundation.Integration.HappinessSvc.SetCustHappinessSurveyAnswersRequest request) {
            return base.Channel.SetCustHappinessSurveyAnswers(request);
        }
        
        public DEWAXP.Foundation.Integration.HappinessSvc.SetCustHappinessSurveyAnswersResponse SetCustHappinessSurveyAnswers(DEWAXP.Foundation.Integration.HappinessSvc.SetCustHappinessSurveyAnswers SetCustHappinessSurveyAnswers1) {
            DEWAXP.Foundation.Integration.HappinessSvc.SetCustHappinessSurveyAnswersRequest inValue = new DEWAXP.Foundation.Integration.HappinessSvc.SetCustHappinessSurveyAnswersRequest();
            inValue.SetCustHappinessSurveyAnswers = SetCustHappinessSurveyAnswers1;
            DEWAXP.Foundation.Integration.HappinessSvc.SetCustHappinessSurveyAnswersResponse1 retVal = ((DEWAXP.Foundation.Integration.HappinessSvc.Config)(this)).SetCustHappinessSurveyAnswers(inValue);
            return retVal.SetCustHappinessSurveyAnswersResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DEWAXP.Foundation.Integration.HappinessSvc.SetCustHappinessSurveyAnswersResponse1> DEWAXP.Foundation.Integration.HappinessSvc.Config.SetCustHappinessSurveyAnswersAsync(DEWAXP.Foundation.Integration.HappinessSvc.SetCustHappinessSurveyAnswersRequest request) {
            return base.Channel.SetCustHappinessSurveyAnswersAsync(request);
        }
        
        public System.Threading.Tasks.Task<DEWAXP.Foundation.Integration.HappinessSvc.SetCustHappinessSurveyAnswersResponse1> SetCustHappinessSurveyAnswersAsync(DEWAXP.Foundation.Integration.HappinessSvc.SetCustHappinessSurveyAnswers SetCustHappinessSurveyAnswers) {
            DEWAXP.Foundation.Integration.HappinessSvc.SetCustHappinessSurveyAnswersRequest inValue = new DEWAXP.Foundation.Integration.HappinessSvc.SetCustHappinessSurveyAnswersRequest();
            inValue.SetCustHappinessSurveyAnswers = SetCustHappinessSurveyAnswers;
            return ((DEWAXP.Foundation.Integration.HappinessSvc.Config)(this)).SetCustHappinessSurveyAnswersAsync(inValue);
        }
    }
}
